CREATE TABLE IF NOT EXISTS material_source_ledger (
  source_id TEXT PRIMARY KEY,
  book_id TEXT NOT NULL UNIQUE,
  catalog_source TEXT NOT NULL,
  book_title TEXT NOT NULL,
  edition TEXT NOT NULL,
  rights_status TEXT NOT NULL CHECK (rights_status IN ('approved', 'pending', 'unknown', 'blocked')),
  review_status TEXT NOT NULL CHECK (review_status IN ('approved', 'needs_review', 'blocked')),
  source_file TEXT NOT NULL,
  extracted_at TEXT NOT NULL,
  transform_log TEXT NOT NULL,
  content_qa_report TEXT NOT NULL,
  qa_word_count INTEGER NOT NULL DEFAULT 0,
  qa_required_blank_rows INTEGER NOT NULL DEFAULT 0,
  qa_rows_with_sentinel INTEGER NOT NULL DEFAULT 0,
  qa_sentinel_value_count INTEGER NOT NULL DEFAULT 0,
  qa_duplicate_headword_count INTEGER NOT NULL DEFAULT 0,
  qa_source_coverage_rate REAL NOT NULL DEFAULT 0,
  qa_example_pair_coverage_rate REAL NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_material_source_ledger_status
  ON material_source_ledger(review_status, rights_status, catalog_source);

WITH source_rows (
  source_id,
  book_id,
  catalog_source,
  book_title,
  edition,
  rights_status,
  review_status,
  source_file,
  extracted_at,
  transform_log,
  content_qa_report,
  qa_word_count,
  qa_required_blank_rows,
  qa_rows_with_sentinel,
  qa_sentinel_value_count,
  qa_duplicate_headword_count,
  qa_source_coverage_rate,
  qa_example_pair_coverage_rate,
  notes,
  created_at,
  updated_at
) AS (
VALUES
('ledger-level-1', 'レベル1-1iowzu9', 'STEADY_STUDY_ORIGINAL', 'レベル1', 'production-2026-06-07', 'approved', 'approved', 'original-wordbank/master_database_refined.csv', '2026-06-07', 'scripts/build-seed-sql.mjs + production content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2267, 0, 0, 0, 0, 0, 0.0009, 'オリジナル単語データベース。未抽出0件確認済み。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-level-2', 'レベル2-1huy6rc', 'STEADY_STUDY_ORIGINAL', 'レベル2', 'production-2026-06-07', 'approved', 'approved', 'original-wordbank/master_database_refined.csv', '2026-06-07', 'scripts/build-seed-sql.mjs + production content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2267, 0, 0, 0, 0, 0, 0, 'オリジナル単語データベース。未抽出0件確認済み。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-level-3', 'レベル3-1i4xsgb', 'STEADY_STUDY_ORIGINAL', 'レベル3', 'production-2026-06-07', 'approved', 'approved', 'original-wordbank/master_database_refined.csv', '2026-06-07', 'scripts/build-seed-sql.mjs + production content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2267, 0, 0, 0, 0, 0, 0, 'オリジナル単語データベース。未抽出0件確認済み。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-level-4', 'レベル4-1jivsx6', 'STEADY_STUDY_ORIGINAL', 'レベル4', 'production-2026-06-07', 'approved', 'approved', 'original-wordbank/master_database_refined.csv', '2026-06-07', 'scripts/build-seed-sql.mjs + production content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2266, 0, 0, 0, 0, 0, 0.0004, 'オリジナル単語データベース。未抽出0件確認済み。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-level-5', 'レベル5-1jsvem5', 'STEADY_STUDY_ORIGINAL', 'レベル5', 'production-2026-06-07', 'approved', 'approved', 'original-wordbank/master_database_refined.csv', '2026-06-07', 'scripts/build-seed-sql.mjs + production content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2266, 0, 0, 0, 0, 0, 0, 'オリジナル単語データベース。未抽出0件確認済み。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-level-6', 'レベル6-1iywlj8', 'STEADY_STUDY_ORIGINAL', 'レベル6', 'production-2026-06-07', 'approved', 'approved', 'original-wordbank/master_database_refined.csv', '2026-06-07', 'scripts/build-seed-sql.mjs + production content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2266, 0, 0, 0, 0, 0, 0.0004, 'オリジナル単語データベース。未抽出0件確認済み。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-duo30', 'duo3-0-6ia9uj', 'LICENSED_PARTNER', 'DUO3.0', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/duo3-0-6ia9uj', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2569, 0, 0, 0, 3, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-look-kobun-337', 'look-古文単語-337-17xlly1', 'LICENSED_PARTNER', 'Look@古文単語 337', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/look-kobun-337', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 337, 0, 0, 0, 12, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-toeic-gold-phrases', 'toeic-gold-phrases-金のフレーズ-1zt7fw', 'LICENSED_PARTNER', 'TOEIC Gold Phrases 金のフレーズ', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/toeic-gold-phrases', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1001, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-mirumiru-kobun-300', 'みるみる覚える古文単語-300-rozh8p', 'LICENSED_PARTNER', 'みるみる覚える古文単語 300', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/mirumiru-kobun-300', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 300, 0, 0, 0, 3, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-corpus4500-4th', 'コーパス4500-4th-edition-1vbql14', 'LICENSED_PARTNER', 'コーパス4500 4th Edition', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/corpus4500-4th', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1983, 0, 0, 0, 7, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-system-5', 'システム英単語-5訂版-raq7ai', 'LICENSED_PARTNER', 'システム英単語 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/system-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2027, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-system-basic-5', 'システム英単語-basic-5訂版-f2z79o', 'LICENSED_PARTNER', 'システム英単語 BASIC 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/system-basic-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1550, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-chunk-standard-2', 'チャンクで英単語-standard-第2版-ffgzmr', 'LICENSED_PARTNER', 'チャンクで英単語 Standard 第2版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/chunk-standard-2', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1120, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-yumejuku', 'ユメジュク-1xk6nyf', 'LICENSED_PARTNER', 'ユメジュク', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/yumejuku', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 800, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-yumetan-red', 'ユメタン赤-1rzu2sl', 'LICENSED_PARTNER', 'ユメタン赤', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/yumetan-red', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1000, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-yumetan-blue', 'ユメタン青-1lwg35v', 'LICENSED_PARTNER', 'ユメタン青', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/yumetan-blue', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1000, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-yumetan-yellow', 'ユメタン黄-jmeeo5', 'LICENSED_PARTNER', 'ユメタン黄', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/yumetan-yellow', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 800, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-kobun-formula-600', '古文単語-formula-600-東進ブックス-wa8fmw', 'LICENSED_PARTNER', '古文単語 Formula 600（東進ブックス）', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/kobun-formula-600', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 600, 0, 0, 0, 10, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-kobun315', '古文単語315-桐原書店-fp9jqh', 'LICENSED_PARTNER', '古文単語315（桐原書店）', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/kobun315', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 315, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-leap-first', '必携英単語leap-初版-18ojfjn', 'LICENSED_PARTNER', '必携英単語LEAP 初版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/leap-first', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1935, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-shin-kakushin-351', '新版-核心古文単語351-iud30p', 'LICENSED_PARTNER', '新版 核心古文単語351', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/shin-kakushin-351', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 351, 0, 0, 0, 4, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-stock3000', '英単語stock3000-6ioln2', 'LICENSED_PARTNER', '英単語Stock3000', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/stock3000', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1528, 0, 0, 0, 2, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-stock4500', '英単語stock4500-yrrewq', 'LICENSED_PARTNER', '英単語Stock4500', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/stock4500', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2154, 0, 0, 0, 2, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-target1200', '英単語ターゲット1200-改訂版-9ycx9l', 'LICENSED_PARTNER', '英単語ターゲット1200 改訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/target1200', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1700, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-target1400', '英単語ターゲット1400-5訂版-14otlwb', 'LICENSED_PARTNER', '英単語ターゲット1400 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/target1400', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1400, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-target1900', '英単語ターゲット1900-6訂版-e5kacl', 'LICENSED_PARTNER', '英単語ターゲット1900 6訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/target1900', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1900, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken1-pass-5', '英検-1級-でる順パス単-5訂版-uc6k8n', 'LICENSED_PARTNER', '英検 1級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken1-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2402, 0, 0, 0, 3, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken2-pass-5', '英検-2級-でる順パス単-5訂版-1yw21m2', 'LICENSED_PARTNER', '英検 2級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken2-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1700, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken3-pass-5', '英検-3級-でる順パス単-5訂版-cm4a0t', 'LICENSED_PARTNER', '英検 3級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken3-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1200, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken4-pass-5', '英検-4級-でる順パス単-5訂版-1kimfrk', 'LICENSED_PARTNER', '英検 4級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken4-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 700, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken5-pass-5', '英検-5級-でる順パス単-5訂版-10gwew3', 'LICENSED_PARTNER', '英検 5級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken5-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 600, 0, 0, 0, 9, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken-pre1-pass-5', '英検-準1級-でる順パス単-5訂版-g2gqjn', 'LICENSED_PARTNER', '英検 準1級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken-pre1-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1900, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken-pre2-pass-5', '英検-準2級-でる順パス単-5訂版-dyyskm', 'LICENSED_PARTNER', '英検 準2級 でる順パス単 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken-pre2-pass-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1500, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken-pre2-plus', '英検-準2級-プラス-重要度順パス単-xp3jzo', 'LICENSED_PARTNER', '英検 準2級 プラス 重要度順パス単', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken-pre2-plus', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1600, 0, 0, 0, 5, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-eiken-pre1-ex', '英検準1級単熟語ex-第2版-1s0bwqo', 'LICENSED_PARTNER', '英検準1級単熟語EX 第2版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/eiken-pre1-ex', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1400, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-idiom-target1000-4', '英熟語ターゲット1000-4訂版-tfagch', 'LICENSED_PARTNER', '英熟語ターゲット1000 4訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/idiom-target1000-4', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1000, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-idiom-target1000-5', '英熟語ターゲット1000-5訂版-g3x5i2', 'LICENSED_PARTNER', '英熟語ターゲット1000 5訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/idiom-target1000-5', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1000, 0, 0, 0, 2, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-koten-330', '見て覚える-読んで解ける-古典単語330-18cyca6', 'LICENSED_PARTNER', '見て覚える 読んで解ける 古典単語330', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/koten-330', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 330, 0, 0, 0, 4, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-lingua-metallica', '話題別英単語リンガメタリカ-vecwcp', 'LICENSED_PARTNER', '話題別英単語リンガメタリカ', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/lingua-metallica', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1910, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-sokutan-advanced', '速読英単語-上級編-2hx36l', 'LICENSED_PARTNER', '速読英単語 上級編', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/sokutan-advanced', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 901, 0, 0, 0, 0, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-sokutan-junior', '速読英単語-中学版-改訂版-1rpw9bt', 'LICENSED_PARTNER', '速読英単語 中学版 改訂版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/sokutan-junior', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2000, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-sokutan-entry-3', '速読英単語-入門編-改訂第3版-ok8mfg', 'LICENSED_PARTNER', '速読英単語 入門編 改訂第3版', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/sokutan-entry-3', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1450, 0, 0, 0, 1, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-sokutan-essential', '速読英単語-必修編-t1zxpc', 'LICENSED_PARTNER', '速読英単語 必修編', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/sokutan-essential', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 1945, 0, 0, 0, 4, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000),
('ledger-teppeki', '鉄緑会-東大英単語熟語-鉄壁-1nv902y', 'LICENSED_PARTNER', '鉄緑会 東大英単語熟語 鉄壁', 'production-2026-06-07', 'pending', 'needs_review', 'licensed-partner/pending/teppeki', '2026-06-07', 'production D1 inventory + content QA after remediation', 'tmp/content-qa/production-content-qa-20260607-after-remediation.json', 2177, 0, 0, 0, 2, 0, 0, '配信中データから台帳初期化。権利資料と出典粒度の確認待ち。', strftime('%s','now') * 1000, strftime('%s','now') * 1000)
)
INSERT INTO material_source_ledger (
  source_id,
  book_id,
  catalog_source,
  book_title,
  edition,
  rights_status,
  review_status,
  source_file,
  extracted_at,
  transform_log,
  content_qa_report,
  qa_word_count,
  qa_required_blank_rows,
  qa_rows_with_sentinel,
  qa_sentinel_value_count,
  qa_duplicate_headword_count,
  qa_source_coverage_rate,
  qa_example_pair_coverage_rate,
  notes,
  created_at,
  updated_at
)
SELECT
  source_rows.source_id,
  source_rows.book_id,
  source_rows.catalog_source,
  source_rows.book_title,
  source_rows.edition,
  source_rows.rights_status,
  source_rows.review_status,
  source_rows.source_file,
  source_rows.extracted_at,
  source_rows.transform_log,
  source_rows.content_qa_report,
  source_rows.qa_word_count,
  source_rows.qa_required_blank_rows,
  source_rows.qa_rows_with_sentinel,
  source_rows.qa_sentinel_value_count,
  source_rows.qa_duplicate_headword_count,
  source_rows.qa_source_coverage_rate,
  source_rows.qa_example_pair_coverage_rate,
  source_rows.notes,
  source_rows.created_at,
  source_rows.updated_at
FROM source_rows
INNER JOIN books b ON b.id = source_rows.book_id
ON CONFLICT(book_id) DO UPDATE SET
  catalog_source = excluded.catalog_source,
  book_title = excluded.book_title,
  edition = excluded.edition,
  rights_status = excluded.rights_status,
  review_status = excluded.review_status,
  source_file = excluded.source_file,
  extracted_at = excluded.extracted_at,
  transform_log = excluded.transform_log,
  content_qa_report = excluded.content_qa_report,
  qa_word_count = excluded.qa_word_count,
  qa_required_blank_rows = excluded.qa_required_blank_rows,
  qa_rows_with_sentinel = excluded.qa_rows_with_sentinel,
  qa_sentinel_value_count = excluded.qa_sentinel_value_count,
  qa_duplicate_headword_count = excluded.qa_duplicate_headword_count,
  qa_source_coverage_rate = excluded.qa_source_coverage_rate,
  qa_example_pair_coverage_rate = excluded.qa_example_pair_coverage_rate,
  notes = excluded.notes,
  updated_at = excluded.updated_at;
