-- Preserve reviewed annotation history when its original evidence changes.
-- Invalidations are durable: restoring a source snapshot or replaying 0056 does
-- not review it again. Clearing a record requires a separate explicit review of
-- the pinned workbook, exact source payload/link and original yellow cell.
-- Only derived exam flags are changed; source archives, words and approval
-- ledgers remain intact. In particular, canonical 0057 keeps its held ready=0.
-- Source/row INSERT OR REPLACE is a replacement even when byte-identical and
-- requires review again. Ordinary unchanged UPSERT / DO NOTHING preserves flags.
-- Annotation inserts with the same locator preserve the normal 0056 replay and
-- the first 0057 insertion; different attempted locators require review.
-- Keep each trigger on one physical line for Wrangler's migration splitter.
CREATE TABLE catalog_word_exam_annotation_invalidations (
  word_id TEXT NOT NULL REFERENCES words(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind = 'AICHI_HIGH_SCHOOL_ENTRANCE'),
  reason TEXT NOT NULL,
  invalidated_at INTEGER NOT NULL,
  PRIMARY KEY (word_id, kind)
);

CREATE TRIGGER invalidate_naru_exam_source_entry_update AFTER UPDATE OF id, source_id, source_key, content_hash, payload_json, ready ON catalog_source_entries WHEN OLD.id IS NOT NEW.id OR OLD.source_id IS NOT NEW.source_id OR OLD.source_key IS NOT NEW.source_key OR OLD.content_hash IS NOT NEW.content_hash OR OLD.payload_json IS NOT NEW.payload_json OR OLD.ready IS NOT NEW.ready BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'SOURCE_ENTRY_CHANGED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.source_entry_id IN (OLD.id, NEW.id) OR (a.match_kind = 'unique_index' AND EXISTS (SELECT 1 FROM catalog_source_entries proof WHERE proof.id = a.source_entry_id AND proof.source_id = OLD.source_id AND (NOT json_valid(OLD.payload_json) OR json_extract(CASE WHEN json_valid(OLD.payload_json) THEN OLD.payload_json ELSE '{}' END, '$.word') = json_extract(CASE WHEN json_valid(proof.payload_json) THEN proof.payload_json ELSE '{}' END, '$.word')))) OR (a.match_kind = 'unique_index' AND EXISTS (SELECT 1 FROM catalog_source_entries proof WHERE proof.id = a.source_entry_id AND proof.source_id = NEW.source_id AND (NOT json_valid(NEW.payload_json) OR json_extract(CASE WHEN json_valid(NEW.payload_json) THEN NEW.payload_json ELSE '{}' END, '$.word') = json_extract(CASE WHEN json_valid(proof.payload_json) THEN proof.payload_json ELSE '{}' END, '$.word')))); END;
CREATE TRIGGER invalidate_naru_exam_source_entry_insert AFTER INSERT ON catalog_source_entries BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'SOURCE_ENTRY_INSERTED_OR_REPLACED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.source_entry_id = NEW.id OR (a.match_kind = 'unique_index' AND EXISTS (SELECT 1 FROM catalog_source_entries proof WHERE proof.id = a.source_entry_id AND proof.source_id = NEW.source_id AND (NOT json_valid(NEW.payload_json) OR json_extract(CASE WHEN json_valid(NEW.payload_json) THEN NEW.payload_json ELSE '{}' END, '$.word') = json_extract(CASE WHEN json_valid(proof.payload_json) THEN proof.payload_json ELSE '{}' END, '$.word')))); END;
CREATE TRIGGER invalidate_naru_exam_source_entry_delete BEFORE DELETE ON catalog_source_entries BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'SOURCE_ENTRY_DELETED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.source_entry_id = OLD.id OR (a.match_kind = 'unique_index' AND EXISTS (SELECT 1 FROM catalog_source_entries proof WHERE proof.id = a.source_entry_id AND proof.source_id = OLD.source_id AND (NOT json_valid(OLD.payload_json) OR json_extract(CASE WHEN json_valid(OLD.payload_json) THEN OLD.payload_json ELSE '{}' END, '$.word') = json_extract(CASE WHEN json_valid(proof.payload_json) THEN proof.payload_json ELSE '{}' END, '$.word')))); END;
CREATE TRIGGER invalidate_naru_exam_workbook_update AFTER UPDATE OF id, series_key, source_file, sha256, archive_json ON catalog_workbook_sources WHEN OLD.id IS NOT NEW.id OR OLD.series_key IS NOT NEW.series_key OR OLD.source_file IS NOT NEW.source_file OR OLD.sha256 IS NOT NEW.sha256 OR OLD.archive_json IS NOT NEW.archive_json BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'WORKBOOK_CHANGED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id IN (OLD.id, NEW.id)); END;
CREATE TRIGGER invalidate_naru_exam_workbook_insert AFTER INSERT ON catalog_workbook_sources BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'WORKBOOK_INSERTED_OR_REPLACED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id = NEW.id); END;
CREATE TRIGGER invalidate_naru_exam_workbook_delete BEFORE DELETE ON catalog_workbook_sources BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'WORKBOOK_DELETED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id = OLD.id); END;
CREATE TRIGGER invalidate_naru_exam_archive_row_update AFTER UPDATE OF source_id, sheet_name, row_number, payload_json ON catalog_workbook_sheet_rows WHEN OLD.source_id IS NOT NEW.source_id OR OLD.sheet_name IS NOT NEW.sheet_name OR OLD.row_number IS NOT NEW.row_number OR OLD.payload_json IS NOT NEW.payload_json BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'EVIDENCE_ROW_CHANGED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE (a.evidence_sheet = OLD.sheet_name AND CAST(ltrim(a.evidence_cell, 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz') AS INTEGER) = OLD.row_number AND EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id = OLD.source_id)) OR (a.evidence_sheet = NEW.sheet_name AND CAST(ltrim(a.evidence_cell, 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz') AS INTEGER) = NEW.row_number AND EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id = NEW.source_id)); END;
CREATE TRIGGER invalidate_naru_exam_archive_row_insert AFTER INSERT ON catalog_workbook_sheet_rows BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'EVIDENCE_ROW_INSERTED_OR_REPLACED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.evidence_sheet = NEW.sheet_name AND CAST(ltrim(a.evidence_cell, 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz') AS INTEGER) = NEW.row_number AND EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id = NEW.source_id); END;
CREATE TRIGGER invalidate_naru_exam_archive_row_delete AFTER DELETE ON catalog_workbook_sheet_rows BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'EVIDENCE_ROW_DELETED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.evidence_sheet = OLD.sheet_name AND CAST(ltrim(a.evidence_cell, 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz') AS INTEGER) = OLD.row_number AND EXISTS (SELECT 1 FROM catalog_source_entries e WHERE e.id = a.source_entry_id AND e.source_id = OLD.source_id); END;
CREATE TRIGGER invalidate_naru_exam_source_link_update AFTER UPDATE OF source_entry_id, word_id, match_kind ON catalog_word_source_links WHEN OLD.source_entry_id IS NOT NEW.source_entry_id OR OLD.word_id IS NOT NEW.word_id OR OLD.match_kind IS NOT NEW.match_kind BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'SOURCE_LINK_CHANGED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.source_entry_id IN (OLD.source_entry_id, NEW.source_entry_id) OR a.word_id IN (OLD.word_id, NEW.word_id); END;
CREATE TRIGGER invalidate_naru_exam_source_link_delete AFTER DELETE ON catalog_word_source_links BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'SOURCE_LINK_DELETED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.source_entry_id = OLD.source_entry_id OR a.word_id = OLD.word_id; END;
CREATE TRIGGER invalidate_naru_exam_source_link_insert AFTER INSERT ON catalog_word_source_links BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'SOURCE_LINK_ADDED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.source_entry_id = NEW.source_entry_id OR a.word_id = NEW.word_id; END;
CREATE TRIGGER invalidate_naru_exam_annotation_replacement BEFORE INSERT ON catalog_word_exam_annotations BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT a.word_id, a.kind, 'ANNOTATION_LOCATOR_REPLACED', CAST(strftime('%s','now') AS INTEGER) * 1000 FROM catalog_word_exam_annotations a WHERE a.word_id = NEW.word_id AND a.kind = NEW.kind AND (a.source_entry_id IS NOT NEW.source_entry_id OR a.evidence_sheet IS NOT NEW.evidence_sheet OR a.evidence_cell IS NOT NEW.evidence_cell OR a.fill_rgb IS NOT NEW.fill_rgb OR a.match_kind IS NOT NEW.match_kind); END;
CREATE TRIGGER invalidate_naru_exam_annotation_update AFTER UPDATE OF word_id, kind, source_entry_id, evidence_sheet, evidence_cell, fill_rgb, match_kind ON catalog_word_exam_annotations WHEN OLD.word_id IS NOT NEW.word_id OR OLD.kind IS NOT NEW.kind OR OLD.source_entry_id IS NOT NEW.source_entry_id OR OLD.evidence_sheet IS NOT NEW.evidence_sheet OR OLD.evidence_cell IS NOT NEW.evidence_cell OR OLD.fill_rgb IS NOT NEW.fill_rgb OR OLD.match_kind IS NOT NEW.match_kind BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT OLD.word_id, OLD.kind, 'ANNOTATION_CHANGED', CAST(strftime('%s','now') AS INTEGER) * 1000 WHERE EXISTS (SELECT 1 FROM words WHERE id = OLD.word_id); INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT NEW.word_id, NEW.kind, 'ANNOTATION_CHANGED', CAST(strftime('%s','now') AS INTEGER) * 1000 WHERE EXISTS (SELECT 1 FROM words WHERE id = NEW.word_id); END;
CREATE TRIGGER invalidate_naru_exam_annotation_delete AFTER DELETE ON catalog_word_exam_annotations BEGIN INSERT OR IGNORE INTO catalog_word_exam_annotation_invalidations (word_id, kind, reason, invalidated_at) SELECT OLD.word_id, OLD.kind, 'ANNOTATION_DELETED', CAST(strftime('%s','now') AS INTEGER) * 1000 WHERE EXISTS (SELECT 1 FROM words WHERE id = OLD.word_id); END;
CREATE TRIGGER clear_invalidated_naru_exam_flag AFTER INSERT ON catalog_word_exam_annotation_invalidations BEGIN UPDATE words SET aichi_exam_appeared = 0 WHERE id = NEW.word_id; END;
CREATE TRIGGER refuse_invalidated_naru_exam_flag_replay AFTER UPDATE OF aichi_exam_appeared ON words WHEN NEW.aichi_exam_appeared = 1 AND EXISTS (SELECT 1 FROM catalog_word_exam_annotation_invalidations i WHERE i.word_id = NEW.id AND i.kind = 'AICHI_HIGH_SCHOOL_ENTRANCE') BEGIN UPDATE words SET aichi_exam_appeared = 0 WHERE id = NEW.id; END;
