import { EnglishLevel, type GrammarCurriculumScopeId } from '../types';

/** Newly authored exercises, never copied from licensed materials or AI review queues. */
export interface OriginalGrammarQuestion {
  id: string;
  scopeId: GrammarCurriculumScopeId;
  level: EnglishLevel;
  recommendedGradeJa: string;
  contextJa: string;
  clozeSentence: string;
  answer: string;
  options: readonly string[];
  sourceSentence: string;
  translationJa: string;
  explanationJa: string;
  distractorReasons: Readonly<Record<string, string>>;
  orderChunks: readonly string[];
  alternateOrders: readonly (readonly number[])[];
  alternativeNotesJa: readonly string[];
}

export interface GrammarQuestionFeedback {
  questionId: string;
  level: EnglishLevel;
  recommendedGradeJa: string;
  translationJa: string;
  explanationJa: string;
  distractorReasons: Readonly<Record<string, string>>;
  alternativeNotesJa: readonly string[];
}

const { A1, A2, B1, B2, C1 } = EnglishLevel;
const gradeByLevel: Record<EnglishLevel, string> = {
  A1: '中1の基礎', A2: '中2〜中3の基礎', B1: '高1〜高2の標準',
  B2: '高2〜大学受験の発展', C1: '大学受験の発展', C2: '発展',
};

const question = (
  key: string, scopeId: GrammarCurriculumScopeId, level: EnglishLevel,
  contextJa: string, clozeSentence: string, answer: string,
  distractors: readonly (readonly [string, string])[],
  translationJa: string, explanationJa: string, chunks: string,
  alternateOrders: readonly (readonly number[])[] = [],
  alternativeNotesJa: readonly string[] = [],
): OriginalGrammarQuestion => ({
  id: `grammar-original-20261003-${key}`, scopeId, level,
  recommendedGradeJa: gradeByLevel[level], contextJa, clozeSentence, answer,
  options: [answer, ...distractors.map(([text]) => text)],
  sourceSentence: clozeSentence.replace('____', answer), translationJa, explanationJa,
  distractorReasons: Object.fromEntries(distractors),
  orderChunks: chunks.split('|'), alternateOrders, alternativeNotesJa,
});

export const ORIGINAL_GRAMMAR_QUESTIONS: readonly OriginalGrammarQuestion[] = [
  question('svo-01', 'basic-svo', A1,
    'ミナの毎朝の習慣を表す文です。', 'Mina ____ apples every morning.', 'eats',
    [['eat', '主語 Mina は三人称単数なので現在形に -s が必要です。'], ['eating', '-ing だけではこの文の述語になりません。'], ['to eat', 'to不定詞だけでは文の述語になりません。']],
    'ミナは毎朝りんごを食べます。', 'Mina が主語、eats が動詞、apples が目的語です。習慣を表す現在形で、単数の主語に合わせます。',
    'Mina|eats|apples|every morning.', [[3, 0, 1, 2]], ['Every morning を文頭に置く語順も自然なので受理します。']),
  question('svo-02', 'basic-svo', A1,
    '私たちは毎回、練習の後にコーチに会います。', 'We ____ our coach after practice.', 'meet',
    [['meets', 'We は複数の主語なので -s を付けません。'], ['meeting', '-ing だけでは述語になりません。'], ['to meet', 'to不定詞はこの位置で述語になりません。']],
    '私たちは練習の後にコーチに会います。', 'We / meet / our coach が主語・動詞・目的語の骨組みです。after practice は「いつ」を補います。',
    'We|meet|our coach|after practice.', [[3, 0, 1, 2]], ['After practice を文頭に置く語順も受理します。']),
  question('be-01', 'be-verb', A1,
    'この靴が現在、自分のものだと言います。', 'These shoes ____ mine.', 'are',
    [['is', 'These shoes は複数なので is ではありません。'], ['am', 'am は主語 I と組み合わせます。'], ['be', '原形 be だけではこの現在形の述語になりません。']],
    'この靴は私のものです。', '複数の主語 These shoes に対応する be動詞は are です。mine は「私のもの」を表します。',
    'These shoes|are|mine.'),
  question('be-02', 'be-verb', A1,
    '今日は今のところ疲れていないと伝えます。', 'I ____ not tired today.', 'am',
    [['is', '主語 I の現在形には is を使いません。'], ['are', '主語 I の現在形には are を使いません。'], ['do', 'tired は形容詞なので、一般動詞用の do ではなく be動詞が必要です。']],
    '私は今日は疲れていません。', 'I am + 形容詞で状態を表します。否定の not は am の後ろです。',
    'I|am not|tired|today.', [[3, 0, 1, 2]], ['Today を文頭に置く語順も受理します。']),
  question('tense-01', 'basic-tense', A1,
    '先週の日曜日に済んだ出来事です。', 'Leo ____ his uncle last Sunday.', 'visited',
    [['visits', 'last Sunday は過去の時点なので現在形は合いません。'], ['visit', '主語 Leo の現在形としても形が合わず、過去の意味も表しません。'], ['visiting', '-ing だけでは過去の述語になりません。']],
    'レオは先週の日曜日におじを訪ねました。', 'last Sunday が過去を示すので visit の過去形 visited を使います。',
    'Leo|visited|his uncle|last Sunday.', [[3, 0, 1, 2]], ['Last Sunday を文頭に置く語順も受理します。']),
  question('tense-02', 'basic-tense', A2,
    '明日の予定を will で表します。', 'We will ____ the museum tomorrow.', 'visit',
    [['visited', 'will の後ろに過去形を置きません。'], ['visits', 'will の後ろは主語にかかわらず原形です。'], ['visiting', 'will の直後に -ing 形を置きません。']],
    '私たちは明日、博物館を訪れる予定です。', '未来を表す will に続く動詞は原形 visit です。',
    'We|will visit|the museum|tomorrow.', [[3, 0, 1, 2]], ['Tomorrow を文頭に置く語順も受理します。']),
  question('progressive-01', 'progressive-aspect', A2,
    '今、姉が泳いでいる途中なのを指さしています。並べ替えでは Look! から始めてください。', 'Look! My sister ____ across the pool.', 'is swimming',
    [['is swim', '進行形は be動詞 + -ing 形です。'], ['are swimming', '単数の My sister に are は合いません。'], ['swimming', '進行形には be動詞が必要です。']],
    '見て！ 姉がプールを泳いで横切っています。', '目の前で進行中の動作は is swimming。主語が単数なので is を使います。',
    'Look!|My sister|is swimming|across the pool.', [], ['並べ替えでは呼びかけ Look! から始めてください。']),
  question('progressive-02', 'progressive-aspect', B1,
    '昨夜8時、夕食を作っている最中に明かりが消えました。', 'I ____ dinner when the lights went out.', 'was cooking',
    [['am cooking', '過去の出来事 went out と、昨夜の文脈に現在進行形は合いません。'], ['were cooking', '主語 I の過去進行形には was を使います。'], ['cooking', '進行形に必要な be動詞がありません。']],
    '明かりが消えたとき、私は夕食を作っていました。', '長く続いていた背景の動作を was cooking、途中で起きた出来事を went out で表します。',
    'I|was cooking|dinner|when the lights went out.', [[3, 0, 1, 2]], ['When 節を文頭に移す語順も受理します。']),
  question('modal-01', 'modal-base-verb', A1,
    '彼女が一人で説明できる能力を表しています。', 'She can ____ the answer without help.', 'explain',
    [['explains', 'can の後ろに三単現の -s は付けません。'], ['explained', 'can の後ろに過去形を置きません。'], ['explaining', 'can の直後は -ing ではなく原形です。']],
    '彼女は助けなしに答えを説明できます。', '助動詞 can + 動詞の原形 explain が正しい形です。',
    'She|can explain|the answer|without help.', [[3, 0, 1, 2]], ['Without help を文頭に置く語順も受理します。']),
  question('modal-02', 'modal-base-verb', A2,
    '看板には「電線に触れることは禁止」と書かれています。禁止を伝えてください。', 'You ____ touch the wires.', 'must not',
    [['do not have to', '「触る必要がない」であり、禁止ではありません。'], ['need not', '「触る必要がない」であり、禁止ではありません。'], ['can', 'この文では「触れてよい・触れられる」となり、禁止の指示と反対です。']],
    '電線に触れてはいけません。', 'must not は禁止。do not have to / need not は必要性がないことなので、意味を区別します。',
    'You|must not touch|the wires.'),
  question('time-01', 'time-preposition-phrase', A1,
    '授業が始まる時計の時刻を言います。', 'Our lesson starts ____ nine o\'clock.', 'at',
    [['in', 'in は年・月などの広い期間に使い、時計の時刻には使いません。'], ['on', 'on は日付や曜日を示します。'], ['during', 'during は行事や期間の「間」を示し、時計の時刻を示しません。']],
    '授業は9時に始まります。', '時計の時刻には at を使います。at nine o’clock で「9時に」。',
    'Our lesson|starts|at nine o\'clock.', [[2, 0, 1]], ['At nine o’clock を文頭に置く語順も受理します。']),
  question('time-02', 'time-preposition-phrase', A2,
    '2021年に住み始めて、今も住んでいます。', 'We have lived here ____ 2021.', 'since',
    [['for', 'for の後ろは「3年間」のような長さです。2021 は開始時点です。'], ['during', 'during は特定期間の中を表し、開始時点からの継続を表しません。'], ['until', 'until は終了時点を表し、今も続くという文脈に合いません。']],
    '私たちは2021年からここに住んでいます。', '継続の開始時点には since。have lived と組み合わせて、開始から現在までを表します。',
    'We|have lived|here|since 2021.', [[3, 0, 1, 2]], ['Since 2021 を文頭に置く語順も受理します。']),
  question('infinitive-01', 'to-infinitive', A2,
    'ユイが美術部に入ることを決めました。', 'Yui decided ____ the art club.', 'to join',
    [['joining', 'decide の目的として「〜すること」は to不定詞を使います。'], ['joins', 'decided の直後に独立した現在形の動詞を置けません。'], ['joined', 'decided の直後にもう一つの過去形を置けません。']],
    'ユイは美術部に入ることにしました。', 'decide to + 動詞の原形で「〜することに決める」です。join the club で「部に入る」。',
    'Yui|decided|to join|the art club.'),
  question('infinitive-02', 'to-infinitive', A2,
    '自転車を買う目的で、お金をためました。', 'I saved money ____ a new bicycle.', 'to buy',
    [['for buy', '前置詞 for の直後に動詞の原形を置けません。'], ['to buying', '目的を表す to不定詞の後ろは原形です。'], ['buy', '目的を示すには to が必要です。']],
    '私は新しい自転車を買うためにお金をためました。', 'to buy は目的を表す不定詞で、「買うために」と訳します。',
    'I|saved|money|to buy a new bicycle.', [[3, 0, 1, 2]], ['目的の To buy ... を文頭に置く語順も受理します。']),
  question('gerund-01', 'gerund', A2,
    'ハルは肖像画を描くことを楽しみます。', 'Haru enjoys ____ portraits.', 'drawing',
    [['to draw', 'enjoy の後ろには to不定詞ではなく動名詞を使います。'], ['draw', 'enjoy の目的語には動詞の原形を置きません。'], ['drawn', '過去分詞はこの位置で「描くこと」を表しません。']],
    'ハルは肖像画を描くのを楽しみます。', 'enjoy + 動名詞。drawing が「描くこと」という名詞の働きをします。',
    'Haru|enjoys|drawing portraits.'),
  question('gerund-02', 'gerund', B1,
    'コーチが短い休憩を取ることを提案しました。', 'The coach suggested ____ a short break.', 'taking',
    [['to take', 'suggest の後ろに to不定詞を直接置く形は使いません。'], ['take', 'suggest の直接の目的語として原形は使いません。'], ['took', '過去形を目的語にできません。']],
    'コーチは短い休憩を取ることを提案しました。', 'suggest + 動名詞で提案内容を表します。suggest that we take ... のような節も別の形として使えます。',
    'The coach|suggested|taking|a short break.', [], ['suggested that we take a short break も可能ですが、今回の語句には that we がありません。']),
  question('participle-01', 'participle-modifier', B1,
    '門のそばに今立っている女性を説明します。', 'The woman ____ by the gate is my aunt.', 'standing',
    [['stands', '名詞を説明する部分に独立した現在形を置くと、文の動詞 is と二重になります。'], ['is standing', '関係代名詞なしで is standing を置くと、文の動詞 is と二重になります。'], ['has stood', '名詞と分詞句の間に関係代名詞がなく、独立した述語を置けません。']],
    '門のそばに立っている女性は私のおばです。', 'the woman を standing by the gate が後ろから修飾します。女性自身が立っているので現在分詞です。',
    'The woman|standing by the gate|is|my aunt.'),
  question('participle-02', 'participle-modifier', B1,
    '1998年に建てられた橋を説明します。', 'The bridge ____ in 1998 still looks new.', 'built',
    [['building', '橋は建てる側ではなく建てられる側なので、能動の現在分詞ではありません。'], ['builds', '修飾部分に独立した現在形を置けません。'], ['build', '原形だけでは「建てられた」という修飾を作れません。']],
    '1998年に建てられた橋は今も新しく見えます。', 'build の過去分詞 built が橋を修飾します。受動の意味なので built in 1998 です。',
    'The bridge|built in 1998|still looks|new.'),
  question('comparison-01', 'comparative', A2,
    'このバッグの方が、もう一つより軽いと比較します。', 'This bag is ____ than that one.', 'lighter',
    [['light', 'than と組み合わせて比較するには比較級が必要です。'], ['lightest', '最上級で「一番軽い」を表す形です。'], ['as light', '同じ程度なら as light as とし、than は使いません。']],
    'このバッグはあのバッグより軽いです。', 'light の比較級は lighter。lighter than ... で「〜より軽い」です。',
    'This bag|is|lighter than|that one.'),
  question('comparison-02', 'comparative', A2,
    '3つのルートのうち、これが一番短いと言います。', 'This is ____ route of the three.', 'the shortest',
    [['the short', '「一番短い」を表すには最上級 shortest が必要です。'], ['short', '単数の数えられる名詞 route の前の限定詞と、最上級の意味が不足します。'], ['as short', '同程度の比較には後ろに as を伴う相手が必要です。']],
    'これは3つのうちで一番短いルートです。', '3つ以上の中で一番なら the + 最上級。short → shortest とします。',
    'This|is|the shortest route|of the three.'),
  question('pronoun-01', 'pronoun-reference', A1,
    'エマが欠席していたので、私はエマ本人に電話しました。', 'Emma was absent, so I called ____ after school.', 'her',
    [['she', 'called の目的語なので主格 she ではなく目的格です。'], ['hers', 'hers は「彼女のもの」であり、電話した相手を表しません。'], ['herself', '主語が I なので、Emma を指す herself を再帰目的語にできません。']],
    'エマは欠席していたので、私は放課後に彼女に電話しました。', '動詞 called の目的語には her を使い、Emma を指します。',
    'Emma was absent|so|I called her|after school.', [[0, 1, 3, 2]], ['結果を表す節の先頭に After school を置く語順も受理します。']),
  question('pronoun-02', 'pronoun-reference', A2,
    '「これらのバッグは私たちのものです」と所有を伝えます。', 'These bags are ____.', 'ours',
    [['our', 'our は後ろに名詞が必要です。ここでは bags を繰り返さない所有代名詞を使います。'], ['us', 'us は目的格で、所有を表しません。'], ['we', 'we は主格で、所有を表しません。']],
    'これらのバッグは私たちのものです。', 'ours は our bags をまとめた「私たちのもの」という所有代名詞です。',
    'These bags|are|ours.'),
  question('conjunction-01', 'when-while-clause', A2,
    '私が料理している「間に」、あなたがテーブルを整えるという同時の動作です。', 'Please set the table ____ I cook dinner.', 'while',
    [['because', '理由「〜だから」になり、同時進行を表す指定に合いません。'], ['although', '逆接「〜だけれど」になり、同時進行の指定に合いません。'], ['if', '条件「もし〜なら」になり、同時進行の指定に合いません。']],
    '私が夕食を作っている間に、テーブルを整えてください。', 'while + 主語 + 動詞で「〜している間に」を表します。後ろには名詞でなく節が続きます。',
    'Please|set the table|while I cook dinner.', [[2, 0, 1]], ['While 節を文頭に置く語順も受理します。']),
  question('conjunction-02', 'when-while-clause', B1,
    'シャワー中に電話が鳴った、その時点を表します。', 'I was taking a shower ____ the phone rang.', 'when',
    [['during', 'during の後ろは名詞句であり、the phone rang という節を直接続けられません。'], ['for', 'for は理由を表す等位接続詞にもなりますが、ここで指定された「電話が鳴ったその時」という意味には合いません。'], ['despite', 'despite の後ろに主語と動詞のある節を直接置けません。']],
    '電話が鳴ったとき、私はシャワーを浴びていました。', 'when が短い出来事の節 the phone rang を導き、過去進行形の背景と結びます。',
    'I|was taking|a shower|when the phone rang.', [[3, 0, 1, 2]], ['When 節を文頭に置く語順も受理します。']),
  question('passive-01', 'passive-voice', A2,
    '窓は清掃をする側ではなく、毎週清掃される側です。', 'The windows ____ every Friday.', 'are cleaned',
    [['is cleaned', 'windows が複数なので be動詞は are です。'], ['cleaned', '受け身には be動詞が必要です。'], ['are cleaning', '能動の進行形であり、「清掃される」を表しません。']],
    '窓は毎週金曜日に清掃されます。', '受け身は be動詞 + 過去分詞。複数の windows に合わせて are cleaned です。',
    'The windows|are cleaned|every Friday.', [[2, 0, 1]], ['Every Friday を文頭に置く語順も受理します。']),
  question('passive-02', 'passive-voice', B1,
    '曲が2010年に作られた、過去の受け身です。', 'This song ____ by a local musician in 2010.', 'was written',
    [['wrote', 'song は書く側ではありません。wrote は能動の過去形です。'], ['was writing', '進行形であり、書かれたという受動の意味を表しません。'], ['is wrote', '受け身には過去分詞 written を使い、過去の文脈には was を使います。']],
    'この曲は2010年に地元の音楽家によって書かれました。', 'write の過去形は wrote、過去分詞は written。過去の受け身は was written です。',
    'This song|was written|by a local musician|in 2010.', [[3, 0, 1, 2], [0, 1, 3, 2]], ['In 2010 の文頭移動と、in 2010 / by ... の順の入れ替えも受理します。']),
  question('perfect-01', 'present-perfect', A2,
    '鍵をなくした結果、今もドアを開けられません。', 'I ____ my keys, so I cannot open the door now.', 'have lost',
    [['lose', '現在形で習慣を表し、今回なくした結果という指定に合いません。'], ['has lost', '主語 I には have を使います。'], ['losing', '-ing だけでは述語になりません。']],
    '鍵をなくしてしまったので、今ドアを開けられません。', 'have + 過去分詞で、過去の出来事が現在に残した結果を表します。lose の過去分詞は lost です。',
    'I|have lost|my keys|so I cannot open the door now.', [], ['別の設問なら I lost my keys も可能です。今回の選択肢には単純過去 lost はありません。']),
  question('perfect-02', 'present-perfect', B1,
    'ミカは5年前に大阪に住み始め、今も住んでいます。', 'Mika has ____ in Osaka for five years.', 'lived',
    [['lives', 'has の後ろは現在形でなく過去分詞です。'], ['living', 'has + -ing だけでは完了形になりません。'], ['live', 'has の後ろに原形を置きません。']],
    'ミカは5年間、大阪に住んでいます。', 'has lived は継続の現在完了。for five years は期間の長さを示します。',
    'Mika|has lived|in Osaka|for five years.', [[3, 0, 1, 2], [0, 1, 3, 2]], ['Mika has been living ... も継続を表せますが、今回の選択肢には been living がありません。', 'For five years の文頭移動と、期間・場所の順の入れ替えも受理します。']),
  question('relative-01', 'relative-clause', B1,
    '隣の席に座っている生徒を説明します。', 'The student ____ sits next to me speaks Korean.', 'who',
    [['which', '人を表す student を受けるこの関係代名詞には which を使いません。'], ['what', 'what は先行詞を含むので、The student の後ろに重ねません。'], ['where', '場所を表す関係副詞であり、sits の主語になれません。']],
    '私の隣に座っている生徒は韓国語を話します。', 'who は人を受ける関係代名詞で、関係節の動詞 sits の主語です。',
    'The student|who sits next to me|speaks|Korean.', [], ['この制限用法では that も正しい別表現です。複数正答にならないよう that は選択肢に入れていません。']),
  question('relative-02', 'relative-clause', B2,
    '祖母が育った場所として町を説明します。', 'This is the town ____ my grandmother grew up.', 'where',
    [['which', 'grow up の場所をつなぐには in which などの前置詞が必要です。which だけでは場所の意味を結べません。'], ['who', '先行詞 town は人ではありません。'], ['whose', 'whose は所有を表し、後ろに名詞を伴います。']],
    'ここは祖母が育った町です。', 'where が「その町で」という場所の働きを担います。the town in which ... と言い換えられます。',
    'This|is|the town|where my grandmother grew up.', [], ['in which も正しい別表現ですが、今回の選択肢は which 単独です。']),
  question('conditional-01', 'first-conditional', A2,
    '明日雨が降った場合の、現実に起こり得る予定です。', 'If it ____ tomorrow, we will play indoors.', 'rains',
    [['will rain', '未来の条件を表す if 節には、この意味で通常 will を入れません。'], ['rained', '明日の実現可能な条件なので現在形を使います。過去形で仮定法にする文脈ではありません。'], ['raining', '-ing だけでは if 節の述語になりません。']],
    '明日雨が降ったら、私たちは屋内で遊びます。', '未来の条件でも if 節には現在形 rains を使い、主節で will play とします。',
    'If it rains tomorrow|we|will play|indoors.', [[1, 2, 3, 0]], ['If 節を文末に置く語順も受理します。']),
  question('conditional-02', 'first-conditional', B1,
    '今出発しなければバスに乗り遅れる、という現実的な条件です。', 'Unless you ____ now, you will miss the bus.', 'leave',
    [['will leave', 'unless が未来の条件を導くこの意味では、節内に現在形を使います。'], ['left', '今からの実現可能な条件を、過去形で表しません。'], ['leaving', '-ing だけでは unless 節の述語になりません。']],
    '今出発しなければ、バスに乗り遅れます。', 'unless は if ... not の意味です。未来の条件には現在形 leave を使います。',
    'Unless you leave now|you|will miss|the bus.', [[1, 2, 3, 0]], ['Unless 節を文末に置く語順も受理します。']),
  question('subjunctive-01', 'subjunctive-mood', B1,
    '実際にあなた本人ではない話し手が、助言として仮定します。', 'If I ____ you, I would apologize.', 'were',
    [['am', '現実と異なる仮定で、主節 would apologize に対応する標準的な形ではありません。'], ['will be', '未来予測を if 節に置く文ではなく、現実と違う仮定です。'], ['are', 'I と are はこの形では一致しません。']],
    '私があなたなら、謝るでしょう。', 'If I were you は助言で使う仮定法の定型です。過去の出来事ではなく現在の仮定です。',
    'If I were you|I|would apologize.', [[1, 2, 0]], ['口語では if I was ... も見られます。今回の選択肢に was はなく、標準的な were を選びます。']),
  question('subjunctive-02', 'subjunctive-mood', B2,
    '昨日は出発が遅く、電車に乗り遅れました。過去の結果を反対に仮定します。', 'If we had left earlier, we ____ the train.', 'would have caught',
    [['will catch', '未来の結果ではなく、実際には起きなかった過去の結果です。'], ['would catch', '現在・未来の結果を表す形であり、昨日の反実仮想の結果には完了形が必要です。'], ['have caught', '仮定に対応する助動詞 would がありません。']],
    'もっと早く出発していたら、私たちはその電車に間に合ったでしょう。', '過去の反実仮想は if + had + 過去分詞、主節は would have + 過去分詞です。catch の過去分詞は caught。',
    'If we had left earlier|we|would have caught|the train.', [[1, 2, 3, 0]], ['If 節を文末に置く語順も受理します。']),
  question('agreement-01', 'subject-verb-agreement', A2,
    '机の一台一台に引き出しがある、現在の状態です。', 'Each of these desks ____ a drawer.', 'has',
    [['have', '主語の中心は複数の desks でなく単数を表す Each です。'], ['having', '-ing だけでは述語になりません。'], ['are have', 'have を使う述語に are を足す形は使いません。']],
    'これらの机にはそれぞれ引き出しがあります。', 'Each of + 複数名詞でも、主語の中心 Each は単数扱いです。現在形は has。',
    'Each of these desks|has|a drawer.'),
  question('agreement-02', 'subject-verb-agreement', B1,
    '戸棚の鍵が今、机の上にあります。鍵は複数です。', 'The keys to the cabinet ____ on my desk.', 'are',
    [['is', '直前の cabinet でなく、主語の中心 keys が複数です。'], ['am', 'am は主語 I に使います。'], ['be', '原形 be だけでは現在形の述語になりません。']],
    '戸棚の鍵は私の机の上にあります。', 'to the cabinet は keys を説明する句。主語の中心 keys に合わせて are を選びます。',
    'The keys to the cabinet|are|on my desk.'),
  question('question-01', 'interrogative-word-order', A1,
    'お兄さんが普段どこに住んでいるかを尋ねます。', 'Where ____ your brother live?', 'does',
    [['do', 'your brother は三人称単数なので does を使います。'], ['is', '一般動詞 live の現在形の疑問文に is を使いません。'], ['are', '一般動詞 live の疑問文に are を使いません。']],
    'あなたのお兄さんはどこに住んでいますか。', '疑問詞 + does + 主語 + 動詞の原形。does が -s の役割を受け持つので live は原形です。',
    'Where|does|your brother|live?'),
  question('question-02', 'interrogative-word-order', B1,
    '「駅がどこにあるか」を、tell me に続く間接疑問で尋ねます。', 'Can you tell me where the station ____?', 'is',
    [['is it', 'the station が既に主語なので、it を重ねません。'], ['does', '場所を表す be動詞の文に does だけを置けません。'], ['be', '主語 the station に対応する現在形 is が必要です。']],
    '駅がどこにあるか教えていただけますか。', '間接疑問は where + 主語 + 動詞の語順です。直接疑問 Where is the station? の語順をそのまま入れません。',
    'Can you|tell me|where the station is?'),
  question('negation-01', 'negation-emphasis', A2,
    '姉は普段、肉を食べないと言います。', 'My sister ____ eat meat.', 'does not',
    [['do not', 'My sister は三人称単数なので does を使います。'], ['is not', '一般動詞 eat の否定に be動詞を足しません。'], ['not does', 'not は does の後ろに置きます。']],
    '姉は肉を食べません。', '一般動詞の現在形の否定は does not + 原形。eat に -s は付けません。',
    'My sister|does not eat|meat.'),
  question('negation-02', 'negation-emphasis', B1,
    '何席かは空いていました。「すべて埋まっていたわけではない」という部分否定です。', 'Not ____ seats were taken.', 'all',
    [['none', 'none はこの位置で名詞 seats を直接修飾しません。'], ['every', 'every の後ろには単数名詞 seat を使います。'], ['no', 'Not no は指定された部分否定の形ではなく、否定を重ねて意味も変わります。']],
    'すべての席が埋まっていたわけではありません。', 'not all は「すべてが〜というわけではない」という部分否定です。no seats という全否定とは区別します。',
    'Not all seats|were|taken.'),
  question('speech-01', 'reported-speech', B1,
    'タロウの「疲れている」という昨日の発言を、過去への時制の一致を用いて報告します。', 'Taro said that he ____ tired.', 'was',
    [['were', 'he の通常の過去形には was を使います。仮定法の文ではありません。'], ['am', '主語 he に am は合いません。'], ['been', 'been だけでは節の述語になりません。']],
    'タロウは疲れていると言いました。', 'said が過去で、発言時の am tired を he was tired として報告します。日本語では報告された内容がその時の状態であることを保ちます。',
    'Taro|said|that he was tired.', [], ['現在も真実の内容なら現在形で報告することもあります。今回は時制の一致を用いる指示で、is は選択肢にありません。']),
  question('speech-02', 'reported-speech', B1,
    'ナナの「準備はできていますか」という yes/no の質問を報告します。', 'Nana asked me ____ I was ready.', 'if',
    [['that', 'yes/no の質問の報告には if / whether を使います。that はここで質問の意味を導きません。'], ['what', 'what は「何」を尋ね、この節で役割を持ちません。'], ['which', '選ぶ対象を尋ねる which では、準備できているかという yes/no の意味になりません。']],
    'ナナは私に準備ができているか尋ねました。', 'asked + 人 + if + 主語 + 動詞で yes/no の質問を報告します。節内は疑問文の倒置をしません。',
    'Nana|asked me|if I was ready.', [], ['whether も正しい言い換えです。単答にするため選択肢には入れていません。']),
  question('verb-pattern-01', 'verb-patterns', A2,
    '先生が私たちに、もう一度その文を読ませました。能動の make を使います。', 'The teacher made us ____ the sentence again.', 'read',
    [['to read', '能動の make + 人 の後ろは to を付けない原形です。'], ['reading', 'この使役構文は -ing でなく原形を使います。'], ['reads', 'made us の後ろに三単現を置きません。']],
    '先生は私たちにその文をもう一度読ませました。', '使役の make + 目的語 + 動詞の原形。過去の made でも後ろは read の原形です。',
    'The teacher|made us|read the sentence|again.', [], ['受け身では We were made to read ... と to が必要です。今回は能動の文です。']),
  question('verb-pattern-02', 'verb-patterns', B1,
    '来週あなたに会うことを楽しみにしています。', 'I look forward to ____ you next week.', 'seeing',
    [['see', 'look forward to の to は前置詞なので、動詞を続けるなら動名詞です。'], ['to see', '前置詞 to の後ろにさらに to不定詞を重ねません。'], ['seen', '過去分詞 seen はここで「会うこと」を表しません。']],
    '来週あなたに会えるのを楽しみにしています。', 'look forward to の to は不定詞の印でなく前置詞。後ろには名詞相当の seeing を置きます。',
    'I|look forward to|seeing you next week.'),
  question('adverb-01', 'adjective-adverb-usage', A2,
    '歌手が「美しく」演奏した、動作の様子を表します。', 'The singer performed ____.', 'beautifully',
    [['beautiful', 'この動作 performed を修飾するには、形容詞ではなく副詞を使います。'], ['beauty', '名詞 beauty はこの位置で動作の様子を表しません。'], ['beautify', '動詞 beautify を performed の後ろに独立した述語として置けません。']],
    '歌手は美しく演奏しました。', '動作 performed の様子を説明する副詞 beautifully を使います。',
    'The singer|performed|beautifully.', [[2, 0, 1], [0, 2, 1]], ['Beautifully の文頭移動と、主語と動詞の間に置く語順も受理します。']),
  question('adverb-02', 'adjective-adverb-usage', B1,
    '箱は十分軽いので、持ち運べます。', 'The box is light ____ to carry.', 'enough',
    [['too', 'too は形容詞の前に置きます。また too light では「軽すぎる」と意味が変わります。'], ['very', 'very は形容詞の前に置き、この形で to不定詞を直接結びません。'], ['many', 'many は可算名詞の数を表し、light を修飾しません。']],
    'その箱は持ち運べるほど十分軽いです。', '形容詞 + enough + to不定詞で「〜するのに十分…」。enough は light の後ろです。',
    'The box|is|light enough|to carry.'),
  question('noun-01', 'noun-usage', A2,
    'コースについての情報をいくらか求めます。', 'Could you give me some ____ about the course?', 'information',
    [['informations', 'information は通常不可算名詞なので複数形の -s を付けません。'], ['inform', 'inform は動詞で、some の後ろの名詞として使えません。'], ['informed', 'informed はこの位置で「情報」という名詞になりません。']],
    'コースについての情報をいくらかいただけますか。', 'information は不可算名詞。some information とし、informations にはしません。',
    'Could you|give me|some information|about the course?'),
  question('noun-02', 'noun-usage', B1,
    '紙を切るために、はさみ1本を必要としています。', 'I need ____ to cut this paper.', 'a pair of scissors',
    [['a scissors', 'scissors は通常複数形扱いなので a を直接付けません。'], ['an scissors', 'an を複数形 scissors に直接付けません。'], ['a pair of scissor', '一組を表す場合も道具の名詞は scissors と複数形にします。']],
    '私はこの紙を切るためにはさみが1本必要です。', 'scissors は複数形の道具名です。1本を数えるなら a pair of scissors とします。',
    'I|need|a pair of scissors|to cut this paper.', [[3, 0, 1, 2]], ['目的の To cut ... を文頭に置く語順も受理します。']),
  question('idiom-01', 'idiomatic-expression', B1,
    '単語の意味や用法を、辞書で調べてください。', 'Please ____ the word in a dictionary.', 'look up',
    [['look after', '「世話をする」という意味で、辞書で意味を調べることではありません。'], ['look for', '「探す」であり、指定された意味や用法を調べる意味とは区別します。'], ['look at', '「見る」であり、指定された辞書で意味を調べる句動詞ではありません。']],
    'その単語を辞書で調べてください。', 'look up は辞書などで情報を調べる句動詞です。look up the word と look the word up の両方が使えます。',
    'Please|look up|the word|in a dictionary.', [[3, 0, 1, 2]], ['look the word up も正しい別表現ですが、今回の look up は1つの語句として提示しています。', 'In a dictionary を文頭に置く語順も受理します。']),
  question('idiom-02', 'idiomatic-expression', B1,
    '牛乳を使い切ってなくなったので、買いに行きました。', 'We ran ____ milk, so I went to buy some.', 'out of',
    [['into', 'run into は遭遇する・ぶつかるという意味で、使い切ったという指定と異なります。'], ['after', 'run after は追いかけるという意味です。'], ['over', 'run over はひく・越えるなどの意味で、使い切った意味になりません。']],
    '牛乳を切らしたので、私は買いに行きました。', 'run out of + 名詞で「〜を使い切る・切らす」です。run の過去形は ran。',
    'We|ran out of milk|so I|went to buy some.'),
  question('conversation-01', 'conversation-expression', A1,
    '相手の「手伝ってくれてありがとう」に、どういたしましてと答えます。', 'You are ____.', 'welcome',
    [['pleased', '「あなたは喜んでいる」であり、お礼に対する定型の返事ではありません。'], ['welcoming', '「歓迎する態度だ」という形容で、お礼への定型の返事とは違います。'], ['welcome to', 'welcome to は後ろに動詞の原形などを必要とし、この空所だけでは文が完成しません。']],
    'どういたしまして。', 'You are welcome. はお礼への返答です。相手に許可する You are welcome to ... とは分けます。',
    'You|are|welcome.'),
  question('conversation-02', 'conversation-expression', A2,
    '窓を開けてほしいと頼まれ、「構いません」と快く承諾します。並べ替えは質問→承諾→行動の順に会話を作ってください。', 'Do you mind opening the window? ____. I will open it now.', 'Not at all',
    [['Yes, I do', 'この質問への yes は「気にする」、つまり頼みを嫌がる意味になり、承諾の指定と合いません。'], ['It is closed', '窓の状態を述べるだけで、構わないという承諾を表しません。'], ['No, I am', 'mind という一般動詞への返事で am は対応しません。']],
    '窓を開けていただけますか。— 全く構いません。今開けます。', 'Do you mind ...? の依頼を受けるなら Not at all / No, I don’t などで「気にしない」と答えます。',
    'Do you mind|opening the window?|Not at all.|I will open it now.', [], ['並べ替えでは質問→承諾→行動の順に会話を作ってください。']),
  question('modal-03', 'modal-base-verb', B1,
    '部屋に明かりがついています。そこにいるはずだ、という現在の強い推量を must で表します。', 'Someone must ____ in the room.', 'be',
    [['is', '推量の must の後ろも動詞の原形です。is は置きません。'], ['was', 'must の直後に過去形は置きません。過去の推量なら must have been とします。'], ['being', 'must の直後に -ing 形だけは置けません。']],
    '誰かがその部屋にいるに違いありません。', 'must + be は現在の状態への強い推量にも使います。must を「義務」とだけ訳さず、この文の推量の意味を読み取ります。',
    'Someone|must be|in the room.'),
  question('comparison-03', 'comparative', B2,
    '練習量が増えるのに連れて、間違いの数が少なくなる比例関係を、標準的な書き言葉で表します。', 'The more you practice, the ____ mistakes you make.', 'fewer',
    [['less', 'mistakes は複数の可算名詞なので、数の少なさには fewer を使います。'], ['few', 'the + 比較級の対応する構文なので原級 few ではありません。'], ['fewest', '比例関係を表す比較級であり、最上級ではありません。']],
    '練習すればするほど、間違いが少なくなります。', 'the + 比較級 ..., the + 比較級 ... は「〜すればするほど…」。可算の mistakes には fewer を使います。',
    'The more you practice|the fewer mistakes|you make.', [], ['口語の less + 複数可算名詞も見られますが、今回は数の比較を表す標準的な書き言葉を練習します。']),
  question('gerund-03', 'gerund', B1,
    '昨日実際にドアを施錠した、その行為の記憶があります。これから忘れずにする、という意味ではありません。', 'I remember ____ the door yesterday.', 'locking',
    [['to lock', 'remember to lock は忘れずに施錠することです。すでに行った行為の記憶を表す今回の意味と異なります。'], ['lock', 'remember の後ろに動詞の原形を直接置くこの形は使いません。'], ['locked', '施錠した行為を名詞として示すには動名詞です。locked を直接続けてもこの構造の目的語になりません。']],
    '私は昨日ドアを施錠したことを覚えています。', 'remember doing は済んだ行為を覚えていること、remember to do はこれからの行為を忘れずに行うことです。時点と意味を合わせて locking を選びます。',
    'I|remember|locking the door yesterday.'),
  question('perfect-03', 'present-perfect', B1,
    'これまで一度も富士山に登った経験がないことを、現在完了で表します。', 'I have never ____ Mount Fuji.', 'climbed',
    [['climb', 'have never の後ろには原形でなく過去分詞を使います。'], ['climbs', 'have の後ろに三単現は置きません。'], ['climbing', 'have + -ing だけでは現在完了になりません。']],
    '私はこれまで一度も富士山に登ったことがありません。', 'have never + 過去分詞は現在までの「一度も〜したことがない」という経験の否定です。climb の過去分詞は climbed。',
    'I|have never climbed|Mount Fuji.'),
  question('perfect-04', 'present-perfect', B2,
    '2時間前から今まで待ち続け、まだ待っています。現在完了進行形を使います。', 'We have ____ for the bus for two hours.', 'been waiting',
    [['being waiting', '完了進行形は have been + -ing であり、being を使いません。'], ['been waited', '進行中の能動の動作には waiting を使います。waited は過去分詞で、この形では指定された動作を表せません。'], ['waiting', 'have + -ing だけでは完了進行形に必要な been がありません。']],
    '私たちは2時間ずっとバスを待っています。', 'have been waiting は過去に始まった動作が現在まで進行していることを表します。for two hours は開始時点でなく継続した長さです。',
    'We|have been waiting|for the bus|for two hours.', [[3, 0, 1, 2], [0, 1, 3, 2]], ['We have waited ... でも継続を表せますが、今回は現在完了進行形の指定で、waited は選択肢にありません。', 'For two hours の文頭移動と、期間・対象の順の入れ替えも受理します。']),
  question('relative-03', 'relative-clause', B2,
    'どの自転車かは既に共有されています。コンマで区切った非制限用法で、購入時期を補足します。', 'My bike, ____ I bought last week, is already broken.', 'which',
    [['that', 'コンマで区切ったこの非制限用法の関係節には that を使いません。'], ['who', '先行詞 bike は人ではありません。'], ['what', 'what は先行詞を含むため、既にある My bike を受けるこの位置には使いません。']],
    '私の自転車は、先週買ったのですが、もう壊れています。', '非制限用法の which は既知の物に補足情報を加えます。制限用法の which / that と違い、コンマで区切るこの形では that を選べません。',
    'My bike,|which I bought last week,|is already|broken.'),
  question('subjunctive-03', 'subjunctive-mood', B2,
    '昨日、鍵を家に置いてきました。その過去の行為を後悔し、そうしなければよかったと願います。', 'I wish I ____ my keys at home yesterday.', 'had not left',
    [['do not leave', '現在の習慣ではなく、済んだ過去の行為への後悔です。'], ['will not leave', '今後の予定でなく、変えられない昨日の出来事を反対に願っています。'], ['would not leave', 'この文脈は過去の事実への後悔なので、wish の後ろは過去完了にします。']],
    '昨日、鍵を家に置いてこなければよかったのに。', 'wish + 過去完了は過去の事実に反する願望です。実際には left したので had not left で反対の内容を示します。',
    'I|wish|I had not left my keys at home yesterday.'),
  question('subjunctive-04', 'subjunctive-mood', C1,
    '昨日地図を買わなかったため、今道に迷っています。昨日の原因を逆に仮定し、現在の結果を述べます。', 'If I had bought a map yesterday, I ____ lost now.', 'would not be',
    [['would not have been', '過去の結果を仮定する形です。今回は今の状態を仮定しているため would not be にします。'], ['will not be', '過去の事実に反する条件なので、確定した未来を表す will ではありません。'], ['am not', '現実には今迷っているため、現実の状態を否定する直説法では指定の仮定を表せません。']],
    '昨日地図を買っていたら、今道に迷っていないでしょう。', '過去の条件 if + had + 過去分詞と、現在の結果 would + 原形を組み合わせる混合仮定法です。yesterday と now の時間差が形を決めます。',
    'If I had bought a map yesterday|I|would not be|lost now.', [[1, 2, 3, 0]]),
  question('speech-03', 'reported-speech', B2,
    '母の「道路の近くでは遊ばないで」という否定の指示を、told me に続けて報告します。', 'My mother told me ____ near the road.', 'not to play',
    [['to not playing', 'to不定詞の後ろは原形です。否定の指示をこの -ing 形では表せません。'], ['do not play', 'told me の後ろに命令文をそのまま置かず、not to + 原形にします。'], ['not play', 'told + 人 の指示内容には to不定詞が必要です。']],
    '母は私に道路の近くで遊ばないように言いました。', '否定の命令を間接話法にすると told + 人 + not to + 原形。命令文の do not をそのまま埋め込みません。',
    'My mother|told me|not to play near the road.', [], ['to not play という語順も見られます。複数正答を避けるため、誤答の to not playing は動詞形そのものが異なります。']),
  question('verb-pattern-03', 'verb-patterns', B2,
    '仕事をいったん中断し、電話に出るために手を止めました。電話に出る行為をやめた意味ではありません。', 'She stopped ____ the phone.', 'to answer',
    [['answering', 'stop answering は電話に出るのをやめる意味です。電話に出るために中断した今回の意味と反対です。'], ['answer', '目的を表す to不定詞の to がなく、stop の後ろに原形を直接続けるこの形は使いません。'], ['answered', 'stopped の後ろに過去形を直接置いて、中断の目的を表すことはできません。']],
    '彼女は電話に出るために手を止めました。', 'stop to do は別の動作を止めて〜すること、stop doing は〜する行為をやめることです。context の中断の目的に合わせて to answer を選びます。',
    'She|stopped|to answer the phone.', [[2, 0, 1]], ['目的の To answer the phone を文頭に置く語順も受理します。']),
  question('agreement-03', 'subject-verb-agreement', B2,
    '参加する生徒の「人数」が今週は昨週より多いと言います。人数を一つの数として述べます。', 'The number of students ____ larger this week.', 'is',
    [['are', '主語の中心は複数の students でなく単数の The number です。'], ['were', '今週の現在の人数で、主語も単数なので were は合いません。'], ['being', '-ing 形だけでは文の述語になりません。']],
    '生徒の人数は今週の方が多いです。', 'The number of ... は「〜の数」で単数扱いです。A number of students are ...（何人もの生徒が…）とは主語の中心が違います。',
    'The number of students|is|larger|this week.', [[3, 0, 1, 2], [0, 3, 1, 2]], ['This week の文頭移動と、主語の後ろに置く語順も受理します。']),
  question('noun-03', 'noun-usage', A2,
    '相手を正直な人だと述べます。冠詞は綴りでなく、honest の最初の音で選びます。', 'He is ____ honest person.', 'an',
    [['a', 'honest の h は発音せず母音で始まるので、ここでは a でなく an です。'], ['many', '単数の person に数を表す many を直接付けません。'], ['two', '単数の person に複数の数 two を直接付けません。']],
    '彼は正直な人です。', 'a / an は後ろの音で選びます。honest は h が発音されず母音で始まるので an honest person です。',
    'He|is|an honest person.'),
];
