import {
  EnglishLevel,
  type GrammarCurriculumScope,
  type GrammarCurriculumScopeId,
  type WorksheetQuestionMode,
} from '../types';

export const GRAMMAR_WORKSHEET_MODES = [
  'GRAMMAR_CLOZE',
  'EN_WORD_ORDER',
  'JA_TRANSLATION_ORDER',
  'JA_TRANSLATION_INPUT',
] as const satisfies readonly WorksheetQuestionMode[];

export type GrammarWorksheetMode = typeof GRAMMAR_WORKSHEET_MODES[number];

export const GRAMMAR_CURRICULUM_SCOPES = [
  {
    id: 'basic-svo',
    category: 'sentence-pattern',
    cefrLevel: EnglishLevel.A1,
    labelJa: '主語 + 動詞 + 目的語',
    labelEn: 'Subject + verb + object',
    descriptionJa: '英単語を基本文型の中で使う範囲です。',
    patternJa: 'だれが / どうする / 何を・何に、の3ますで英文の骨組みを作ります。',
    examFocusJa: '高校受験では語順、大学受験では長い文の主語と動詞の見抜き方が得点源です。',
    commonMistakeJa: '日本語の順番に引っ張られて、動詞や目的語を後ろへ置きすぎるミスが出やすいです。',
    automationDrillJa: '3語から始めて、同じ型で10文を短時間で作り、知る段階から自動化へ移します。',
    threeSlotFrameJa: '主語 / 動詞 / 目的語',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'be-verb',
    category: 'verb-form',
    cefrLevel: EnglishLevel.A1,
    labelJa: 'be動詞を使った文',
    labelEn: 'Be-verb sentences',
    descriptionJa: '状態や性質を表す be 動詞の文を扱います。',
    patternJa: '主語 + be動詞 + 状態・性質で、何であるか・どんな状態かを表します。',
    examFocusJa: '主語に合わせた am / is / are と、過去形 was / were の対応が基本点になります。',
    commonMistakeJa: '一般動詞の文に be を足したり、be動詞を抜かしたりするミスが起きやすいです。',
    automationDrillJa: 'I am / It is / They are を口に出して、状態を入れ替える練習を短く反復します。',
    threeSlotFrameJa: '主語 / be動詞 / 状態',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'modal-base-verb',
    category: 'verb-form',
    cefrLevel: EnglishLevel.A1,
    labelJa: '助動詞 + 動詞の原形',
    labelEn: 'Modal + base verb',
    descriptionJa: 'can / should / must などの助動詞と動詞の原形を扱います。',
    patternJa: '主語 + 助動詞 + 動詞の原形で、可能・義務・推量を足します。',
    examFocusJa: '助動詞の後ろを原形に保てるかが、並び替え・空所補充で狙われます。',
    commonMistakeJa: 'can uses のように、助動詞の後ろに三単現や過去形を置くミスが出やすいです。',
    automationDrillJa: 'can / should / must を1つ選び、同じ動詞を原形のまま入れて声に出します。',
    threeSlotFrameJa: '主語 / 助動詞+動詞 / 目的語',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'time-preposition-phrase',
    category: 'phrase',
    cefrLevel: EnglishLevel.A1,
    labelJa: '時を表す副詞句',
    labelEn: 'Time preposition phrases',
    descriptionJa: 'before / after / during など、時を表す句を扱います。',
    patternJa: '文の骨組みに before / after / during などの時を表すかざりを足します。',
    examFocusJa: '時の句がどこにかかるかを読む力は、和訳と長文読解の両方で効きます。',
    commonMistakeJa: 'before class などのまとまりを切り離し、語順や訳の係り先を見失いやすいです。',
    automationDrillJa: '3ます文に「いつ」を1つ足し、短い文から自然に長くする練習をします。',
    threeSlotFrameJa: '主語 / 動詞 / 目的語 + いつ',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'to-infinitive',
    category: 'verb-form',
    cefrLevel: EnglishLevel.A2,
    labelJa: 'to不定詞',
    labelEn: 'To-infinitive',
    descriptionJa: '目的や予定を表す to + 動詞の原形を扱います。',
    patternJa: 'to + 動詞の原形で、目的・予定・名詞的な働きを作ります。',
    examFocusJa: '「何のために」「何すること」の区別は、和訳・空所補充で頻出です。',
    commonMistakeJa: 'to の後ろを過去形や -ing にしたり、目的の訳を落としたりしやすいです。',
    automationDrillJa: 'want to / need to / try to を使い、動詞の原形を入れて短文を作ります。',
    threeSlotFrameJa: '主語 / 動詞 / to+動詞',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'gerund',
    category: 'verb-form',
    cefrLevel: EnglishLevel.A2,
    labelJa: '動名詞',
    labelEn: 'Gerund',
    descriptionJa: '動詞を名詞のように使う -ing 形を扱います。',
    patternJa: '動詞 + ing を名詞のように使い、「すること」を表します。',
    examFocusJa: 'enjoy / finish / avoid など、後ろに -ing を取りやすい動詞が狙われます。',
    commonMistakeJa: 'enjoy to study のように、不定詞と動名詞を混同するミスが出やすいです。',
    automationDrillJa: 'enjoy / finish / keep の後ろに -ing を入れて、型ごと覚えます。',
    threeSlotFrameJa: '主語 / 動詞 / -ing',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'comparative',
    category: 'comparison',
    cefrLevel: EnglishLevel.A2,
    labelJa: '比較表現',
    labelEn: 'Comparatives',
    descriptionJa: 'more / -er / than などの比較表現を扱います。',
    patternJa: '形容詞・副詞に more / -er と than を組み合わせ、差を表します。',
    examFocusJa: '比較対象と差の方向を正しく訳せるかが、受験和訳で差になります。',
    commonMistakeJa: 'than の後ろの比較対象を落としたり、more と -er を重ねたりしやすいです。',
    automationDrillJa: 'A is more ... than B の型で、身近な名詞を入れ替えて練習します。',
    threeSlotFrameJa: 'A / be動詞 / 比較 + than B',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'when-while-clause',
    category: 'clause',
    cefrLevel: EnglishLevel.A2,
    labelJa: 'when / while 節',
    labelEn: 'When / while clauses',
    descriptionJa: '時や同時進行を表す副詞節を扱います。',
    patternJa: 'when / while + 主語 + 動詞で、時や同時進行のまとまりを作ります。',
    examFocusJa: '節の中の主語と動詞を見抜き、主節との関係を訳す力が問われます。',
    commonMistakeJa: 'when 節を名詞のかたまりと誤読したり、主節との順番だけで訳を決めたりしやすいです。',
    automationDrillJa: 'When I ..., I ... の形で、短い場面を声に出してつなげます。',
    threeSlotFrameJa: '時の節 / 主語 / 動詞',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'passive-voice',
    category: 'verb-form',
    cefrLevel: EnglishLevel.B1,
    labelJa: '受け身',
    labelEn: 'Passive voice',
    descriptionJa: 'be動詞 + 過去分詞で、される側を主語にする文を扱います。',
    patternJa: 'be動詞 + 過去分詞で、「される側」を主語にして表します。',
    examFocusJa: 'by の有無に関係なく、誰が何をされたのかを補って訳す力が必要です。',
    commonMistakeJa: '過去形と過去分詞を混同したり、日本語で主語を曖昧にしすぎたりしやすいです。',
    automationDrillJa: 'It is used / They are chosen のように、be + 過去分詞をまとまりで反復します。',
    threeSlotFrameJa: 'されるもの / be+過去分詞 / by+行為者',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'present-perfect',
    category: 'verb-form',
    cefrLevel: EnglishLevel.B1,
    labelJa: '現在完了',
    labelEn: 'Present perfect',
    descriptionJa: 'have / has + 過去分詞で経験・継続・完了を表す文を扱います。',
    patternJa: 'have / has + 過去分詞で、過去から今につながる意味を表します。',
    examFocusJa: '経験・継続・完了のどれに近いかを文脈で判断する和訳が重要です。',
    commonMistakeJa: '単純な過去形として訳し、今とのつながりを落とすミスが出やすいです。',
    automationDrillJa: 'I have ... / She has ... を使い、already / ever / for を足して練習します。',
    threeSlotFrameJa: '主語 / have+過去分詞 / 補足',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'relative-clause',
    category: 'clause',
    cefrLevel: EnglishLevel.B1,
    labelJa: '関係詞節',
    labelEn: 'Relative clauses',
    descriptionJa: 'who / which / that などで名詞を説明する節を扱います。',
    patternJa: '名詞 + who / which / that + 主語・動詞で、前の名詞を後ろから説明します。',
    examFocusJa: 'どの名詞を説明しているかを固定できると、長文和訳の精度が上がります。',
    commonMistakeJa: '関係詞節を別の文として切ってしまい、説明先の名詞を取り違えやすいです。',
    automationDrillJa: 'the word that ... のように、説明される名詞を指で押さえて読みます。',
    threeSlotFrameJa: '名詞 / 関係詞節 / 文の続き',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
  {
    id: 'first-conditional',
    category: 'clause',
    cefrLevel: EnglishLevel.B1,
    labelJa: '条件を表す文',
    labelEn: 'First conditional',
    descriptionJa: 'if 節と will などで、条件と結果を表す文を扱います。',
    patternJa: 'If + 主語 + 現在形, 主語 + will ... で、条件と結果を表します。',
    examFocusJa: 'if 節では未来のことでも現在形を使う点が、空所補充と並び替えで問われます。',
    commonMistakeJa: 'If 節に will を入れすぎたり、条件と結果の主語を混同したりしやすいです。',
    automationDrillJa: 'If I study, I will ... の形で、条件と結果をセットにして口に出します。',
    threeSlotFrameJa: '条件 / 主語 / 結果',
    targetQuestionModes: ['GRAMMAR_CLOZE', 'EN_WORD_ORDER', 'JA_TRANSLATION_ORDER', 'JA_TRANSLATION_INPUT'],
  },
] as const satisfies readonly GrammarCurriculumScope[];

export const DEFAULT_GRAMMAR_SCOPE_ID_BY_MODE: Record<GrammarWorksheetMode, GrammarCurriculumScopeId> = {
  GRAMMAR_CLOZE: 'basic-svo',
  EN_WORD_ORDER: 'basic-svo',
  JA_TRANSLATION_ORDER: 'basic-svo',
  JA_TRANSLATION_INPUT: 'basic-svo',
};

export const GRAMMAR_CURRICULUM_SCOPE_LABELS: Record<GrammarCurriculumScopeId, string> = (
  GRAMMAR_CURRICULUM_SCOPES.reduce((labels, scope) => ({
    ...labels,
    [scope.id]: scope.labelJa,
  }), {} as Record<GrammarCurriculumScopeId, string>)
);
