import {
  EnglishLevel,
  type GrammarCurriculumCategoryId,
  type GrammarCurriculumGroupId,
  type GrammarCurriculumScope,
  type GrammarCurriculumScopeId,
  type WorksheetQuestionMode,
} from '../types';

export const GRAMMAR_WORKSHEET_MODES = [
  'GRAMMAR_CLOZE',
  'EN_WORD_ORDER',
  'JA_TRANSLATION_ORDER',
  'JA_TRANSLATION_INPUT',
] as const satisfies readonly WorksheetQuestionMode[];

export type GrammarWorksheetMode = typeof GRAMMAR_WORKSHEET_MODES[number];

export const GRAMMAR_CURRICULUM_GROUP_LABELS: Record<GrammarCurriculumGroupId, string> = {
  'sentence-basics': '文の土台',
  'verb-system': '動詞まわり',
  'verbals-and-modifiers': '準動詞・修飾',
  'clauses-and-connectors': '節・接続',
  'nominals-and-function-words': '名詞句・機能語',
  'syntax-control': '語順・一致・情報構造',
  'usage-and-expression': '語法・表現',
};

export const GRAMMAR_CURRICULUM_CATEGORY_LABELS: Record<GrammarCurriculumCategoryId, string> = {
  'sentence-patterns': '文型',
  tense: '時制',
  voice: '態',
  modals: '助動詞',
  subjunctive: '仮定法',
  infinitive: '不定詞',
  gerund: '動名詞',
  participle: '分詞',
  comparison: '比較',
  pronouns: '代名詞',
  relatives: '関係詞',
  conjunctions: '接続詞',
  prepositions: '前置詞',
  agreement: '主語と動詞の一致',
  'questions-and-word-order': '疑問文と語順',
  'negation-ellipsis-emphasis': '否定・省略・強調',
  'sequence-and-speech': '時制の一致と話法',
  'verb-usage': '動詞語法',
  'adjective-adverb-usage': '形容詞・副詞語法',
  'noun-usage': '名詞語法',
  idioms: 'イディオム',
  conversation: '会話表現',
};

export const GRAMMAR_CURRICULUM_GROUPS = Object.entries(GRAMMAR_CURRICULUM_GROUP_LABELS).map(([id, labelJa]) => ({
  id: id as GrammarCurriculumGroupId,
  labelJa,
}));

export const GRAMMAR_CURRICULUM_CATEGORIES = Object.entries(GRAMMAR_CURRICULUM_CATEGORY_LABELS).map(([id, labelJa]) => ({
  id: id as GrammarCurriculumCategoryId,
  labelJa,
}));

const allModes = (): WorksheetQuestionMode[] => [...GRAMMAR_WORKSHEET_MODES];
const noJapaneseOrderModes = (): WorksheetQuestionMode[] => [
  'GRAMMAR_CLOZE',
  'EN_WORD_ORDER',
  'JA_TRANSLATION_INPUT',
];

const defineScope = (
  scope: Omit<GrammarCurriculumScope, 'groupLabelJa' | 'curriculumCategoryLabelJa'>,
): GrammarCurriculumScope => ({
  ...scope,
  groupLabelJa: GRAMMAR_CURRICULUM_GROUP_LABELS[scope.groupId],
  curriculumCategoryLabelJa: GRAMMAR_CURRICULUM_CATEGORY_LABELS[scope.curriculumCategoryId],
});

export const GRAMMAR_CURRICULUM_SCOPES = [
  defineScope({
    id: 'basic-svo',
    category: 'sentence-pattern',
    groupId: 'sentence-basics',
    curriculumCategoryId: 'sentence-patterns',
    cefrLevel: EnglishLevel.A1,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '主語 + 動詞 + 目的語',
    labelEn: 'Subject + verb + object',
    descriptionJa: '英単語を基本文型の中で使う範囲です。',
    patternJa: 'だれが / どうする / 何を・何に、の3ますで英文の骨組みを作ります。',
    examFocusJa: '高校受験では語順、大学受験では長い文の主語と動詞の見抜き方が得点源です。',
    commonMistakeJa: '日本語の順番に引っ張られて、動詞や目的語を後ろへ置きすぎるミスが出やすいです。',
    automationDrillJa: '3語から始めて、同じ型で10文を短時間で作り、知る段階から自動化へ移します。',
    threeSlotFrameJa: '主語 / 動詞 / 目的語',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'be-verb',
    category: 'verb-form',
    groupId: 'verb-system',
    curriculumCategoryId: 'verb-usage',
    cefrLevel: EnglishLevel.A1,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.A2,
    labelJa: 'be動詞を使った文',
    labelEn: 'Be-verb sentences',
    descriptionJa: '状態や性質を表す be 動詞の文を扱います。',
    patternJa: '主語 + be動詞 + 状態・性質で、何であるか・どんな状態かを表します。',
    examFocusJa: '主語に合わせた am / is / are と、過去形 was / were の対応が基本点になります。',
    commonMistakeJa: '一般動詞の文に be を足したり、be動詞を抜かしたりするミスが起きやすいです。',
    automationDrillJa: 'I am / It is / They are を口に出して、状態を入れ替える練習を短く反復します。',
    threeSlotFrameJa: '主語 / be動詞 / 状態',
    targetQuestionModes: noJapaneseOrderModes(),
  }),
  defineScope({
    id: 'basic-tense',
    category: 'verb-form',
    groupId: 'verb-system',
    curriculumCategoryId: 'tense',
    cefrLevel: EnglishLevel.A1,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '基本時制',
    labelEn: 'Basic tense',
    descriptionJa: '現在・過去・未来の時制を、文脈の時間表現と合わせて扱います。',
    patternJa: '動詞の形と yesterday / now / tomorrow などの時を表す語を結びます。',
    examFocusJa: '時を表す語から動詞の形を選ぶ空所補充と、和訳で時制を落とさないことが基本点です。',
    commonMistakeJa: '日本語では時制が曖昧でも、英語では動詞の形を変える必要がある点を忘れやすいです。',
    automationDrillJa: '同じ主語と動詞で yesterday / today / tomorrow を入れ替え、形の変化を声に出します。',
    threeSlotFrameJa: '時 / 主語 / 動詞',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'progressive-aspect',
    category: 'verb-form',
    groupId: 'verb-system',
    curriculumCategoryId: 'tense',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B1,
    labelJa: '進行形',
    labelEn: 'Progressive aspect',
    descriptionJa: 'be動詞 + -ing で、進行中の動作を表す文を扱います。',
    patternJa: '主語 + be動詞 + 動詞ing で「今している」「その時していた」を表します。',
    examFocusJa: '現在形との違いと、be動詞を落とさない語順が並び替えで狙われます。',
    commonMistakeJa: 'studying だけで述語にしたり、be動詞と一般動詞を重ねたりしやすいです。',
    automationDrillJa: 'I am / She is / They are に -ing を続けて、主語と be動詞をセットで反復します。',
    threeSlotFrameJa: '主語 / be+ing / 目的語',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'modal-base-verb',
    category: 'verb-form',
    groupId: 'verb-system',
    curriculumCategoryId: 'modals',
    cefrLevel: EnglishLevel.A1,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '助動詞 + 動詞の原形',
    labelEn: 'Modal + base verb',
    descriptionJa: 'can / should / must などの助動詞と動詞の原形を扱います。',
    patternJa: '主語 + 助動詞 + 動詞の原形で、可能・義務・推量を足します。',
    examFocusJa: '助動詞の後ろを原形に保てるかが、並び替え・空所補充で狙われます。',
    commonMistakeJa: 'can uses のように、助動詞の後ろに三単現や過去形を置くミスが出やすいです。',
    automationDrillJa: 'can / should / must を1つ選び、同じ動詞を原形のまま入れて声に出します。',
    threeSlotFrameJa: '主語 / 助動詞+動詞 / 目的語',
    targetQuestionModes: noJapaneseOrderModes(),
  }),
  defineScope({
    id: 'time-preposition-phrase',
    category: 'phrase',
    groupId: 'nominals-and-function-words',
    curriculumCategoryId: 'prepositions',
    cefrLevel: EnglishLevel.A1,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '時を表す副詞句',
    labelEn: 'Time preposition phrases',
    descriptionJa: 'before / after / during など、時を表す句を扱います。',
    patternJa: '文の骨組みに before / after / during などの時を表すかざりを足します。',
    examFocusJa: '時の句がどこにかかるかを読む力は、和訳と長文読解の両方で効きます。',
    commonMistakeJa: 'before class などのまとまりを切り離し、語順や訳の係り先を見失いやすいです。',
    automationDrillJa: '3ます文に「いつ」を1つ足し、短い文から自然に長くする練習をします。',
    threeSlotFrameJa: '主語 / 動詞 / 目的語 + いつ',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'to-infinitive',
    category: 'verb-form',
    groupId: 'verbals-and-modifiers',
    curriculumCategoryId: 'infinitive',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B1,
    labelJa: 'to不定詞',
    labelEn: 'To-infinitive',
    descriptionJa: '目的や予定を表す to + 動詞の原形を扱います。',
    patternJa: 'to + 動詞の原形で、目的・予定・名詞的な働きを作ります。',
    examFocusJa: '「何のために」「何すること」の区別は、和訳・空所補充で頻出です。',
    commonMistakeJa: 'to の後ろを過去形や -ing にしたり、目的の訳を落としたりしやすいです。',
    automationDrillJa: 'want to / need to / try to を使い、動詞の原形を入れて短文を作ります。',
    threeSlotFrameJa: '主語 / 動詞 / to+動詞',
    targetQuestionModes: noJapaneseOrderModes(),
  }),
  defineScope({
    id: 'gerund',
    category: 'verb-form',
    groupId: 'verbals-and-modifiers',
    curriculumCategoryId: 'gerund',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B1,
    labelJa: '動名詞',
    labelEn: 'Gerund',
    descriptionJa: '動詞を名詞のように使う -ing 形を扱います。',
    patternJa: '動詞 + ing を名詞のように使い、「すること」を表します。',
    examFocusJa: 'enjoy / finish / avoid など、後ろに -ing を取りやすい動詞が狙われます。',
    commonMistakeJa: 'enjoy to study のように、不定詞と動名詞を混同するミスが出やすいです。',
    automationDrillJa: 'enjoy / finish / keep の後ろに -ing を入れて、型ごと覚えます。',
    threeSlotFrameJa: '主語 / 動詞 / -ing',
    targetQuestionModes: noJapaneseOrderModes(),
  }),
  defineScope({
    id: 'participle-modifier',
    category: 'phrase',
    groupId: 'verbals-and-modifiers',
    curriculumCategoryId: 'participle',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.B1,
    levelMax: EnglishLevel.B2,
    labelJa: '分詞の後置修飾',
    labelEn: 'Participle modifiers',
    descriptionJa: '-ing / 過去分詞で名詞を後ろから説明する形を扱います。',
    patternJa: '名詞 + 現在分詞 / 過去分詞で、名詞の状態や動作を説明します。',
    examFocusJa: '修飾される名詞と分詞の関係を見抜けると、長い英文の和訳が安定します。',
    commonMistakeJa: '分詞句を別の文として読んだり、能動・受動の向きを取り違えたりしやすいです。',
    automationDrillJa: 'the word used in class のように、説明される名詞を先に押さえてから分詞句を読みます。',
    threeSlotFrameJa: '名詞 / 分詞句 / 文の続き',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'comparative',
    category: 'comparison',
    groupId: 'verbals-and-modifiers',
    curriculumCategoryId: 'comparison',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '比較表現',
    labelEn: 'Comparatives',
    descriptionJa: 'more / -er / than などの比較表現を扱います。',
    patternJa: '形容詞・副詞に more / -er と than を組み合わせ、差を表します。',
    examFocusJa: '比較対象と差の方向を正しく訳せるかが、受験和訳で差になります。',
    commonMistakeJa: 'than の後ろの比較対象を落としたり、more と -er を重ねたりしやすいです。',
    automationDrillJa: 'A is more ... than B の型で、身近な名詞を入れ替えて練習します。',
    threeSlotFrameJa: 'A / be動詞 / 比較 + than B',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'pronoun-reference',
    category: 'phrase',
    groupId: 'nominals-and-function-words',
    curriculumCategoryId: 'pronouns',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '代名詞の指示',
    labelEn: 'Pronoun reference',
    descriptionJa: 'it / they / this / those などが何を指すかを扱います。',
    patternJa: '名詞を受ける代名詞を使い、同じ語のくり返しを避けます。',
    examFocusJa: 'it や they の指す内容を本文中で特定する力は、長文読解で頻出です。',
    commonMistakeJa: '直前の名詞だけで判断し、数や意味が合わない先行詞を選びやすいです。',
    automationDrillJa: '名詞を言ってから it / they に置き換え、数と意味の対応を声に出します。',
    threeSlotFrameJa: '名詞 / 代名詞 / 文の続き',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'when-while-clause',
    category: 'clause',
    groupId: 'clauses-and-connectors',
    curriculumCategoryId: 'conjunctions',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B1,
    labelJa: 'when / while 節',
    labelEn: 'When / while clauses',
    descriptionJa: '時や同時進行を表す副詞節を扱います。',
    patternJa: 'when / while + 主語 + 動詞で、時や同時進行のまとまりを作ります。',
    examFocusJa: '節の中の主語と動詞を見抜き、主節との関係を訳す力が問われます。',
    commonMistakeJa: 'when 節を名詞のかたまりと誤読したり、主節との順番だけで訳を決めたりしやすいです。',
    automationDrillJa: 'When I ..., I ... の形で、短い場面を声に出してつなげます。',
    threeSlotFrameJa: '時の節 / 主語 / 動詞',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'passive-voice',
    category: 'verb-form',
    groupId: 'verb-system',
    curriculumCategoryId: 'voice',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '受け身',
    labelEn: 'Passive voice',
    descriptionJa: 'be動詞 + 過去分詞で、される側を主語にする文を扱います。',
    patternJa: 'be動詞 + 過去分詞で、「される側」を主語にして表します。',
    examFocusJa: 'by の有無に関係なく、誰が何をされたのかを補って訳す力が必要です。',
    commonMistakeJa: '過去形と過去分詞を混同したり、日本語で主語を曖昧にしすぎたりしやすいです。',
    automationDrillJa: 'It is used / They are chosen のように、be + 過去分詞をまとまりで反復します。',
    threeSlotFrameJa: 'されるもの / be+過去分詞 / by+行為者',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'present-perfect',
    category: 'verb-form',
    groupId: 'verb-system',
    curriculumCategoryId: 'tense',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '現在完了',
    labelEn: 'Present perfect',
    descriptionJa: 'have / has + 過去分詞で経験・継続・完了を表す文を扱います。',
    patternJa: 'have / has + 過去分詞で、過去から今につながる意味を表します。',
    examFocusJa: '経験・継続・完了のどれに近いかを文脈で判断する和訳が重要です。',
    commonMistakeJa: '単純な過去形として訳し、今とのつながりを落とすミスが出やすいです。',
    automationDrillJa: 'I have ... / She has ... を使い、already / ever / for を足して練習します。',
    threeSlotFrameJa: '主語 / have+過去分詞 / 補足',
    targetQuestionModes: noJapaneseOrderModes(),
  }),
  defineScope({
    id: 'relative-clause',
    category: 'clause',
    groupId: 'clauses-and-connectors',
    curriculumCategoryId: 'relatives',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.B1,
    levelMax: EnglishLevel.B2,
    labelJa: '関係詞節',
    labelEn: 'Relative clauses',
    descriptionJa: 'who / which / that などで名詞を説明する節を扱います。',
    patternJa: '名詞 + who / which / that + 主語・動詞で、前の名詞を後ろから説明します。',
    examFocusJa: 'どの名詞を説明しているかを固定できると、長文和訳の精度が上がります。',
    commonMistakeJa: '関係詞節を別の文として切ってしまい、説明先の名詞を取り違えやすいです。',
    automationDrillJa: 'the word that ... のように、説明される名詞を指で押さえて読みます。',
    threeSlotFrameJa: '名詞 / 関係詞節 / 文の続き',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'first-conditional',
    category: 'clause',
    groupId: 'clauses-and-connectors',
    curriculumCategoryId: 'subjunctive',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B1,
    labelJa: '条件を表す文',
    labelEn: 'First conditional',
    descriptionJa: 'if 節と will などで、条件と結果を表す文を扱います。',
    patternJa: 'If + 主語 + 現在形, 主語 + will ... で、条件と結果を表します。',
    examFocusJa: 'if 節では未来のことでも現在形を使う点が、空所補充と並び替えで問われます。',
    commonMistakeJa: 'If 節に will を入れすぎたり、条件と結果の主語を混同したりしやすいです。',
    automationDrillJa: 'If I study, I will ... の形で、条件と結果をセットにして口に出します。',
    threeSlotFrameJa: '条件 / 主語 / 結果',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'subjunctive-mood',
    category: 'clause',
    groupId: 'clauses-and-connectors',
    curriculumCategoryId: 'subjunctive',
    cefrLevel: EnglishLevel.B2,
    levelMin: EnglishLevel.B1,
    levelMax: EnglishLevel.C1,
    labelJa: '仮定法',
    labelEn: 'Subjunctive mood',
    descriptionJa: '現実と違う仮定や願望を表す would / could / had + 過去分詞を扱います。',
    patternJa: 'If + 主語 + 過去形, 主語 + would ... で、現実と違う仮定を表します。',
    examFocusJa: '時制が過去形でも現在の仮定を表す点と、帰結節の助動詞が頻出です。',
    commonMistakeJa: '単純な過去として訳したり、if 節と主節の時制のずれを見落としたりしやすいです。',
    automationDrillJa: 'If I were ..., I would ... を固定型として声に出し、仮定と結果を対で覚えます。',
    threeSlotFrameJa: '仮定 / 主語 / 結果',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'subject-verb-agreement',
    category: 'sentence-pattern',
    groupId: 'syntax-control',
    curriculumCategoryId: 'agreement',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '主語と動詞の一致',
    labelEn: 'Subject-verb agreement',
    descriptionJa: '主語の単数・複数に合わせた動詞の形を扱います。',
    patternJa: '主語の中心を見つけ、その数に合わせて動詞を選びます。',
    examFocusJa: '長い主語や of 句に惑わされず、動詞の単複を決める問題で得点源になります。',
    commonMistakeJa: '直前の名詞につられて、主語の中心と違う動詞形を選びやすいです。',
    automationDrillJa: 'The list of ... is / The students are のように、主語の中心に線を引いて読みます。',
    threeSlotFrameJa: '主語の中心 / 動詞 / 補足',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'interrogative-word-order',
    category: 'sentence-pattern',
    groupId: 'syntax-control',
    curriculumCategoryId: 'questions-and-word-order',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '疑問文と語順',
    labelEn: 'Questions and word order',
    descriptionJa: '疑問詞・助動詞・主語の順番を扱います。',
    patternJa: '疑問詞 + 助動詞 / be動詞 + 主語 + 動詞で、質問の形を作ります。',
    examFocusJa: '並び替えでは、疑問詞の後ろに続く助動詞と主語の位置が狙われます。',
    commonMistakeJa: '日本語の語順に引っ張られ、主語と助動詞の順番を逆にしやすいです。',
    automationDrillJa: 'What do you ...? / Where is ...? を短く反復し、疑問文の先頭3語を固めます。',
    threeSlotFrameJa: '疑問詞 / 助動詞 / 主語+動詞',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'negation-emphasis',
    category: 'sentence-pattern',
    groupId: 'syntax-control',
    curriculumCategoryId: 'negation-ellipsis-emphasis',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '否定・強調',
    labelEn: 'Negation and emphasis',
    descriptionJa: 'not / never / do 強調 / not only など、否定や強調の形を扱います。',
    patternJa: '否定語や強調語を置く位置で、文の焦点を変えます。',
    examFocusJa: '部分否定・強調構文・倒置の入口として、長文和訳で意味を落とさないことが重要です。',
    commonMistakeJa: 'not のかかる範囲を広く取りすぎたり、強調の do を普通の動詞として読んだりしやすいです。',
    automationDrillJa: 'I do use ... / I do not use ... の対で、肯定・否定・強調の違いを声に出します。',
    threeSlotFrameJa: '主語 / 否定・強調 / 動詞',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'reported-speech',
    category: 'clause',
    groupId: 'clauses-and-connectors',
    curriculumCategoryId: 'sequence-and-speech',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.B1,
    levelMax: EnglishLevel.B2,
    labelJa: '時制の一致と話法',
    labelEn: 'Sequence of tense and reported speech',
    descriptionJa: 'said that / told me that などで、発言内容を別の文に組み込む形を扱います。',
    patternJa: '伝達動詞 + that 節で、発言や考えを文の中に入れます。',
    examFocusJa: '直接話法から間接話法への書き換えと、時制のずれが文法問題で狙われます。',
    commonMistakeJa: '発言時点と現在時点を混同し、that 節の時制や代名詞を直さないミスが出やすいです。',
    automationDrillJa: 'He says that ... / He said that ... を並べ、時制の変化だけを取り出して練習します。',
    threeSlotFrameJa: '伝達動詞 / that節 / 時制',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'verb-patterns',
    category: 'verb-form',
    groupId: 'usage-and-expression',
    curriculumCategoryId: 'verb-usage',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '動詞語法',
    labelEn: 'Verb patterns',
    descriptionJa: 'want 人 to do / make 人 do / spend time doing など、動詞ごとの型を扱います。',
    patternJa: '動詞ごとに後ろへ続く形をセットで覚えます。',
    examFocusJa: '空所補充では、意味よりも動詞が要求する形を知っているかが問われます。',
    commonMistakeJa: '意味が近い動詞を同じ型で使い、to do と doing や原形を混同しやすいです。',
    automationDrillJa: 'want to / help 人 do / spend time doing のように、動詞と後ろの形を1つの単位で反復します。',
    threeSlotFrameJa: '主語 / 動詞 / 続く形',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'adjective-adverb-usage',
    category: 'phrase',
    groupId: 'usage-and-expression',
    curriculumCategoryId: 'adjective-adverb-usage',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '形容詞・副詞語法',
    labelEn: 'Adjective and adverb usage',
    descriptionJa: '形容詞と副詞の置き場所や、enough / too などの型を扱います。',
    patternJa: '形容詞は名詞や状態を、副詞は動詞・形容詞・文全体を説明します。',
    examFocusJa: '形容詞と副詞の選択、too ... to / enough to の語順が頻出です。',
    commonMistakeJa: '形容詞を動詞の後ろにそのまま置いたり、副詞の位置で意味を変えてしまいやすいです。',
    automationDrillJa: 'very useful / use it carefully / useful enough to ... を短く並べて位置を確認します。',
    threeSlotFrameJa: '説明される語 / 形容詞・副詞 / 補足',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'noun-usage',
    category: 'phrase',
    groupId: 'nominals-and-function-words',
    curriculumCategoryId: 'noun-usage',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.A2,
    levelMax: EnglishLevel.B2,
    labelJa: '名詞語法',
    labelEn: 'Noun usage',
    descriptionJa: '可算・不可算、冠詞、名詞句のまとまりを扱います。',
    patternJa: '名詞の数・冠詞・前後の説明語をまとめて名詞句として読みます。',
    examFocusJa: '冠詞や単複、information など不可算名詞の扱いが空所補充で狙われます。',
    commonMistakeJa: '日本語に冠詞がないため、a / the / 複数形の判断を抜かしやすいです。',
    automationDrillJa: 'a word / the word / useful information のように、名詞の前後をセットで声に出します。',
    threeSlotFrameJa: '冠詞 / 名詞 / 説明語',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'idiomatic-expression',
    category: 'phrase',
    groupId: 'usage-and-expression',
    curriculumCategoryId: 'idioms',
    cefrLevel: EnglishLevel.B1,
    levelMin: EnglishLevel.B1,
    levelMax: EnglishLevel.C1,
    labelJa: 'イディオム',
    labelEn: 'Idiomatic expressions',
    descriptionJa: 'look forward to / take part in など、まとまりで意味を作る表現を扱います。',
    patternJa: '複数語を1つの表現として読み、直訳だけに頼らず意味を取ります。',
    examFocusJa: '前置詞の組み合わせや、見た目と意味がずれる熟語が選択問題で狙われます。',
    commonMistakeJa: '単語ごとに訳してしまい、表現全体の意味や後ろに続く形を取り違えやすいです。',
    automationDrillJa: 'look forward to using ... のように、表現と後ろの形をセットで反復します。',
    threeSlotFrameJa: '熟語 / 続く形 / 意味',
    targetQuestionModes: allModes(),
  }),
  defineScope({
    id: 'conversation-expression',
    category: 'phrase',
    groupId: 'usage-and-expression',
    curriculumCategoryId: 'conversation',
    cefrLevel: EnglishLevel.A2,
    levelMin: EnglishLevel.A1,
    levelMax: EnglishLevel.B1,
    labelJa: '会話表現',
    labelEn: 'Conversation expressions',
    descriptionJa: 'Could you ...? / Would you like ...? など、会話で使う決まり文句を扱います。',
    patternJa: '相手への依頼・提案・確認を、丁寧な文の形で表します。',
    examFocusJa: '会話文では、前後の流れに合う依頼・応答・提案の表現が問われます。',
    commonMistakeJa: '直訳で命令文のように強くなったり、返答表現の丁寧さを見落としたりしやすいです。',
    automationDrillJa: 'Could you ...? / Would you like ...? を場面ごとに短く言い換えます。',
    threeSlotFrameJa: '丁寧表現 / 主語 / 動詞',
    targetQuestionModes: allModes(),
  }),
] as const satisfies readonly GrammarCurriculumScope[];

export const DEFAULT_GRAMMAR_SCOPE_ID_BY_MODE: Record<GrammarWorksheetMode, GrammarCurriculumScopeId> = {
  GRAMMAR_CLOZE: 'basic-svo',
  EN_WORD_ORDER: 'basic-svo',
  JA_TRANSLATION_ORDER: 'basic-svo',
  JA_TRANSLATION_INPUT: 'basic-svo',
};

export const GRAMMAR_CURRICULUM_SCOPE_LABELS: Record<GrammarCurriculumScopeId, string> = (
  GRAMMAR_CURRICULUM_SCOPES.reduce((labels, scope) => ({
    ...labels,
    [scope.id]: scope.labelJa,
  }), {} as Record<GrammarCurriculumScopeId, string>)
);
