export const MOBILE_FLOW_SCENARIOS = {
  demoLogin: 'demo-login',
  onboarding: 'student-onboarding',
  dashboardCta: 'dashboard-cta',
  study: 'short-study',
  learnedOnlyQuiz: 'learned-only-quiz',
  quizExitConfirm: 'quiz-exit-confirm',
  writingSubmit: 'writing-submit',
  writingFeedback: 'writing-feedback',
};

export const MOBILE_FLOW_TEST_IDS = {
  demoLoginStudent: 'demo-login-student',
  onboardingProfile: 'onboarding-profile',
  onboardingTest: 'onboarding-test',
  diagnosticOption: 'diagnostic-option',
  studentDashboard: 'student-dashboard',
  demoBannerToggle: 'demo-banner-toggle',
  studentHeroPrimaryCta: 'student-hero-primary-cta',
  quizQuestionCard: 'quiz-question-card',
  quizShowOptions: 'quiz-show-options',
  quizSetupView: 'quiz-setup-view',
  quizSelectionLearnedOnly: 'quiz-selection-learned_only',
  quizEmptyState: 'quiz-empty-state',
  quizBackButton: 'quiz-back-button',
  quizSetupPrimaryCta: 'quiz-setup-primary-cta',
  quizReadyView: 'quiz-ready-view',
  quizReadyStart: 'quiz-ready-start',
  quizRunningView: 'quiz-running-view',
  quizExitConfirmDialog: 'quiz-exit-confirm-dialog',
  quizExitCancel: 'quiz-exit-cancel',
  quizExitConfirm: 'quiz-exit-confirm',
  quizResultView: 'quiz-result-view',
  studyCardFront: 'study-card-front',
  studyCardBack: 'study-card-back',
  studyFlipButton: 'study-flip-button',
  studyRate0: 'study-rate-0',
  studyRate3: 'study-rate-3',
  studyFinishExit: 'study-finish-exit',
  writingStudentSection: 'writing-student-section',
  writingStudentFileInput: 'writing-student-file-input',
  writingFeedbackMobileView: 'writing-feedback-mobile-view',
  writingFeedbackComment: 'writing-feedback-comment',
  writingFeedbackStrengths: 'writing-feedback-strengths',
  writingFeedbackImprovements: 'writing-feedback-improvements',
  writingFeedbackCorrected: 'writing-feedback-corrected',
  writingFeedbackTranscript: 'writing-feedback-transcript',
  writingFeedbackAssets: 'writing-feedback-assets',
};

export const MOBILE_FLOW_BUTTON_LABELS = {
  onboardingGrade: '中学3年生',
  onboardingConfidence: '学校英語はだいたい分かる',
  onboardingStart: '診断を始める',
  onboardingNext: '次へ',
  onboardingResult: '判定を見る',
  onboardingCommit: 'このレベルで学習を始める',
  writingNextToFiles: 'ファイル選択へ進む',
  writingNextToSubmit: '最終送信へ進む',
  writingSubmitted: '答案を提出しました',
};

export const MOBILE_FLOW_WRITING = {
  transcriptPlaceholder: 'OCR が読み取りにくいときのために、書いた英文をおおまかに入力できます。',
  feedbackSectionOrder: [
    'writing-feedback-comment',
    'writing-feedback-strengths',
    'writing-feedback-improvements',
    'writing-feedback-corrected',
    'writing-feedback-transcript',
    'writing-feedback-assets',
  ],
};
