import {
  type BookMetadata,
  type LearningPlan,
  type LearningPreference,
  type UserProfile,
} from '../types';
import { useStudentDashboardMutations } from './useStudentDashboardMutations';
import { useStudentDashboardUiState } from './useStudentDashboardUiState';

interface UseStudentDashboardControllerParams {
  user: UserProfile;
  learningPlan: LearningPlan | null;
  learningPreference: LearningPreference | null;
  planningBooks: BookMetadata[];
  canGenerateAiPlan: boolean;
  onUserUpdate: (user: UserProfile) => void;
  refreshDashboard: () => Promise<void>;
  updateLearningPlan: (plan: LearningPlan | null) => void;
  updateLearningPreference: (preference: LearningPreference | null) => void;
  removeMyBook: (bookId: string) => void;
}

export const useStudentDashboardController = ({
  user,
  learningPlan,
  learningPreference,
  planningBooks,
  canGenerateAiPlan,
  onUserUpdate,
  refreshDashboard,
  updateLearningPlan,
  updateLearningPreference,
  removeMyBook,
}: UseStudentDashboardControllerParams) => {
  const {
    generatingPlan,
    showLibrary,
    setShowLibrary,
    showProgressDetails,
    setShowProgressDetails,
    showAccountDetails,
    setShowAccountDetails,
    showCreateModal,
    setShowCreateModal,
    showSettingsModal,
    setShowSettingsModal,
    showOnboarding,
    setShowOnboarding,
    showPlanEditModal,
    setShowPlanEditModal,
    pageNotice,
    setPageNotice,
    pendingDeleteBook,
    setPendingDeleteBook,
    editDailyGoal,
    setEditDailyGoal,
    selectedPlanBooks,
    togglePlanBook,
    createMode,
    setCreateMode,
    rawText,
    setRawText,
    uploadFile,
    setUploadFile,
    newBookTitle,
    setNewBookTitle,
    creating,
    setCreating,
    errorMsg,
    setErrorMsg,
    handleFileChange,
    handleDeleteBook,
    editName,
    setEditName,
    editGrade,
    setEditGrade,
    editStudyMode,
    setEditStudyMode,
    editTargetExam,
    setEditTargetExam,
    editTargetScore,
    setEditTargetScore,
    editExamDate,
    setEditExamDate,
    editWeeklyStudyDays,
    setEditWeeklyStudyDays,
    editDailyStudyMinutes,
    setEditDailyStudyMinutes,
    editWeakSkillFocus,
    setEditWeakSkillFocus,
    editMotivationNote,
    setEditMotivationNote,
    editIntensity,
    setEditIntensity,
    editDisplayFontSize,
    setEditDisplayFontSize,
    editDisplayDensity,
    setEditDisplayDensity,
    isSavingProfile,
    setIsSavingProfile,
    setGeneratingPlan,
  } = useStudentDashboardUiState({ user, learningPlan, learningPreference });

  const {
    handleGeneratePlan,
    handleUpdatePlan,
    handleCreatePhrasebook,
    confirmDeleteBook,
    handleSaveProfile,
  } = useStudentDashboardMutations({
    user,
    learningPlan,
    learningPreference,
    planningBooks,
    canGenerateAiPlan,
    onUserUpdate,
    refreshDashboard,
    updateLearningPlan,
    updateLearningPreference,
    removeMyBook,
    setPageNotice,
    setGeneratingPlan,
    selectedPlanBooks,
    editDailyGoal,
    setShowPlanEditModal,
    setCreating,
    setErrorMsg,
    setShowCreateModal,
    setRawText,
    setNewBookTitle,
    setUploadFile,
    pendingDeleteBook,
    setPendingDeleteBook,
    setIsSavingProfile,
    setShowSettingsModal,
    editName,
    editGrade,
    editStudyMode,
    editTargetExam,
    editTargetScore,
    editExamDate,
    editWeeklyStudyDays,
    editDailyStudyMinutes,
    editWeakSkillFocus,
    editMotivationNote,
    editIntensity,
    editDisplayFontSize,
    editDisplayDensity,
    createMode,
    rawText,
    uploadFile,
    newBookTitle,
  });

  return {
    generatingPlan,
    showLibrary,
    setShowLibrary,
    showProgressDetails,
    setShowProgressDetails,
    showAccountDetails,
    setShowAccountDetails,
    showCreateModal,
    setShowCreateModal,
    showSettingsModal,
    setShowSettingsModal,
    showOnboarding,
    setShowOnboarding,
    showPlanEditModal,
    setShowPlanEditModal,
    pageNotice,
    setPageNotice,
    pendingDeleteBook,
    setPendingDeleteBook,
    editDailyGoal,
    setEditDailyGoal,
    selectedPlanBooks,
    handleGeneratePlan,
    togglePlanBook,
    handleUpdatePlan,
    createMode,
    setCreateMode,
    rawText,
    setRawText,
    uploadFile,
    newBookTitle,
    setNewBookTitle,
    creating,
    errorMsg,
    handleFileChange,
    handleCreatePhrasebook,
    handleDeleteBook,
    confirmDeleteBook,
    editName,
    setEditName,
    editGrade,
    setEditGrade,
    editStudyMode,
    setEditStudyMode,
    editTargetExam,
    setEditTargetExam,
    editTargetScore,
    setEditTargetScore,
    editExamDate,
    setEditExamDate,
    editWeeklyStudyDays,
    setEditWeeklyStudyDays,
    editDailyStudyMinutes,
    setEditDailyStudyMinutes,
    editWeakSkillFocus,
    setEditWeakSkillFocus,
    editMotivationNote,
    setEditMotivationNote,
    editIntensity,
    setEditIntensity,
    editDisplayFontSize,
    setEditDisplayFontSize,
    editDisplayDensity,
    setEditDisplayDensity,
    isSavingProfile,
    handleSaveProfile,
  };
};

export default useStudentDashboardController;
